In [64]:
import pandas as pd

month = 202512
productgroupset_map = {
    '灶具':['灶具'],
    '蒸烤微合计':['烤箱','蒸箱','微波炉','蒸烤烹饪机','蒸烤微烹饪机','蒸微'],
    '灶集成':['灶消烹饪机','灶蒸烹饪机','灶蒸烤烹饪机','灶烤烹饪机']}
productgroupsset_map_1 = {
                    '吸油烟机': '吸油烟机',
                    '灶具': '灶具',
                    '烤箱': '蒸烤微合计',
                    '蒸箱': '蒸烤微合计',
                    '微波炉': '蒸烤微合计',
                    '蒸烤烹饪机': '蒸烤微合计',
                    '蒸烤微烹饪机': '蒸烤微合计',
                    '蒸微': '蒸烤微合计',
                    '灶消烹饪机': '灶集成',
                    '灶蒸烹饪机': '灶集成',
                    '灶蒸烤烹饪机': '灶集成',
                    '灶烤烹饪机': '灶集成',
                    '消毒柜': '消毒柜',
                    '热水器': '热水器',
                    '两用炉': '热水器',
                    '家用净水机': '家用净水机',
                    '商用净水机': '净水机',
                    '水槽洗碗机': '水槽洗碗机',
                    '嵌入式洗碗机': '嵌入式洗碗机'
                    }

### 数据清洗

#### 导入MBOM数据

In [65]:
df1 = pd.read_excel(fr"D:\000物料报表\通用化报告\{month}\mbom-12-31-1000-1001.XLSX")
df2 = pd.read_excel(fr"D:\000物料报表\通用化报告\{month}\mbom-12-31-1002.XLSX")
df3 = pd.read_excel(fr"D:\000物料报表\通用化报告\{month}\mbom-12-31-1003.XLSX")
df4 = pd.read_excel(fr"D:\000物料报表\通用化报告\{month}\mbom-12-31-1004-1005.XLSX")

In [66]:
df_mbom = pd.concat([df1,df2,df3,df4],axis=0)

#### 生产订单数据导入

In [67]:
df_work_list = pd.read_excel(fr"D:\000物料报表\通用化报告\{month}\生产订单-12-31.XLSX")

In [68]:
# 处理数据格式
df_mbom['最终父项物料编码'] = df_mbom['最终父项物料编码'].astype(str).str[:13]
# 处理数据格式
df_work_list['物料编码'] = df_work_list['物料编号'].astype(str).str[:13]

#### 导入PLM数据

In [69]:
# PLM产品数据导入
df_plm = pd.read_excel(fr"D:\000物料报表\通用化报告\{month}\产品生命周期状态全表.xlsx")
df_plm['物料号'] = df_plm['物料号'].astype(str).str.strip().str[:13]
# df_plm

e:\python\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

#### 导入零件族数据

In [70]:
# 零件族数据导入
df_part_family = pd.read_excel(fr"D:\000物料报表\通用化报告\{month}\零件族.xlsx")
df_part_family['物料编码'] = df_part_family['物料编码'].astype(str).str.strip().str[:13]
df_part_family

                 物料编码     物料名称               零件系列
0       1101000208060   内油网焊接件   内油网-吸油烟机-结构3TMGY
1       1101000208070   外油网焊接件   外油网-吸油烟机-结构3TMGY
2       1101000310840   导风板打磨件    导风板-吸油烟机-结构3TMG
3       1101000310850    油杯焊接件    油杯-吸油烟机-结构4TMGY
4       1101000310860   导油板焊接件    导油板-吸油烟机-结构2TMG
...               ...      ...                ...
136290            nan      工艺管           工艺管-吸油烟机
136291            nan  内机电机隔热棉       内机电机隔热棉-吸油烟机
136292            nan     电容支架  电容支架-蒸烤微-运动&水路TMG
136293            nan      控制板             控制板-电气
136294            nan    上开关组件            开关组件-电气

[136295 rows x 3 columns]

#### 导入物料组数据

In [71]:
df_product_group = pd.read_excel(fr"D:\000物料报表\通用化报告\202512\整机物料组.XLSX")
df_product_group = df_product_group.astype(str)
df_product_group['物料编码'] = df_product_group['物料编码'].str[:13]
df_product_group

               物料编码       物料组        物料组描述
0     1001000100030  10010001      整机油烟机备留
1     1001000100031  10010001      整机油烟机备留
2     1001000100032  10010001      整机油烟机备留
3     1001000100033  10010001      整机油烟机备留
4     1001000100034  10010001      整机油烟机备留
...             ...       ...          ...
7204  1024000200023  10240002  整机集成式洗碗机X系列
7205  1024000200024  10240002  整机集成式洗碗机X系列
7206  1024000200025  10240002  整机集成式洗碗机X系列
7207  1026000100000  10260001   整机智慧水槽一代平台
7208  1026000100001  10260001   整机智慧水槽一代平台

[7209 rows x 3 columns]

#### 导出11开头的零件明细（df_mbom），这里对最终父+子进行了去重

In [ ]:
# 只保留子项物料编码以11开头的
# 只保留最终父项物料编码和子项物料编码
df_mbom = df_mbom[['最终父项物料编码','子项物料编码']].drop_duplicates().reset_index(drop=True)
df_mbom = df_mbom[df_mbom['子项物料编码'].str.startswith('11')].reset_index(drop=True)
df_mbom.to_excel(fr"D:\000物料报表\通用化报告\202512\需要导出信息的零件明细.xlsx", index=False)

#### 匹配产品信息以及零件系列信息以及物料组数据

In [73]:
# 把产品相关信息匹配进去
df_merged_mbom_plm = pd.merge(df_mbom, df_plm[['物料号', '标准型号', '国内/海外', '产品组','产品状态']].drop_duplicates().reset_index(drop=True), left_on='最终父项物料编码',right_on='物料号', how='left')
print(len(df_merged_mbom_plm))
# 把零件系列信息匹配进去
df_merged_mbom_plm['零件系列'] = df_merged_mbom_plm['子项物料编码'].map(dict(zip(df_part_family['物料编码'],df_part_family['零件系列']))).astype(str)
# 把物料组信息匹配进去
df_merged_mbom_plm['物料组描述'] = df_merged_mbom_plm['最终父项物料编码'].map(dict(zip(df_product_group['物料编码'],df_product_group['物料组描述']))).astype(str)
df_merged_mbom_plm.head()

648742

,最终父项物料编码,子项物料编码,物料号,标准型号,国内/海外,产品组,产品状态,零件系列,物料组描述
0,1001000500258,110100051870A,1001000500258,JQ26TA,国内,吸油烟机,停止发货,装饰罩-吸油烟机-结构4TMGY,整机油烟机JQ系列
1,1001000500373,110100051870A,1001000500373,JQ31A,国内,吸油烟机,量产,装饰罩-吸油烟机-结构4TMGY,整机油烟机JQ系列
2,1001000500379,110100051870A,1001000500379,JQ35A,国内,吸油烟机,停止销售,装饰罩-吸油烟机-结构4TMGY,整机油烟机JQ系列
3,1001000500384,1101000532650,1001000500384,NaN,海外,吸油烟机,量产,箱体-吸油烟机-结构2TMG,整机油烟机JQ系列
4,1001000500384,1101000532690,1001000500384,NaN,海外,吸油烟机,量产,金属面板-吸油烟机-结构5TMG,整机油烟机JQ系列

In [74]:
print(df_merged_mbom_plm[df_merged_mbom_plm['零件系列'].str.contains('手紧螺母')]['子项物料编码'].value_counts())
df_merged_mbom_plm

子项物料编码
1101000913630    223
1123000300870     51
1101001506620     19
110100210524A      9
1101001510280      7
1101000540140      4
1101000539210      2
1101000532480      1
1101000942700      1
110100081838A      1
1101000539060      1
1101002301470      1
Name: count, dtype: int64

,最终父项物料编码,子项物料编码,物料号,标准型号,国内/海外,产品组,产品状态,零件系列,物料组描述
0,1001000500258,110100051870A,1001000500258,JQ26TA,国内,吸油烟机,停止发货,装饰罩-吸油烟机-结构4TMGY,整机油烟机JQ系列
1,1001000500373,110100051870A,1001000500373,JQ31A,国内,吸油烟机,量产,装饰罩-吸油烟机-结构4TMGY,整机油烟机JQ系列
2,1001000500379,110100051870A,1001000500379,JQ35A,国内,吸油烟机,停止销售,装饰罩-吸油烟机-结构4TMGY,整机油烟机JQ系列
3,1001000500384,1101000532650,1001000500384,NaN,海外,吸油烟机,量产,箱体-吸油烟机-结构2TMG,整机油烟机JQ系列
4,1001000500384,1101000532690,1001000500384,NaN,海外,吸油烟机,量产,金属面板-吸油烟机-结构5TMG,整机油烟机JQ系列
...,...,...,...,...,...,...,...,...,...
648737,1013000800009,1113000803090,1013000800009,YCZ-JT1500-02-X20Max,国内,家用净水机,量产,散热片-净水机,整机净水机嵌入式净饮系列
648738,1013000800009,1113000803330,1013000800009,YCZ-JT1500-02-X20Max,国内,家用净水机,量产,散热片-净水机,整机净水机嵌入式净饮系列
648739,1013000800009,1113000803320,1013000800009,YCZ-JT1500-02-X20Max,国内,家用净水机,量产,散热水箱盖-净水机,整机净水机嵌入式净饮系列
648740,1013000800009,1113000803060,1013000800009,YCZ-JT1500-02-X20Max,国内,家用净水机,量产,散热水箱-净水机,整机净水机嵌入式净饮系列
648741,1013000800009,1113000803100,1013000800009,YCZ-JT1500-02-X20Max,国内,家用净水机,量产,水箱温度探针-净水机,整机净水机嵌入式净饮系列

#### 按照零件进行筛选

In [75]:
# 按照零件信息进行筛选
# 剔除掉虚拟物料和服务专用配件
df_filter1 = pd.read_excel(fr"D:\000物料报表\通用化报告\202512\虚拟-服务专用配件-图号判断.XLSX")
df_merged_mbom_plm['物料描述'] = df_merged_mbom_plm['子项物料编码'].map(dict(zip(df_filter1['物料编码'], df_filter1['物料描述'])))
df_merged_mbom_plm['图号'] = df_merged_mbom_plm['子项物料编码'].map(dict(zip(df_filter1['物料编码'], df_filter1['图号'])))
df_merged_mbom_plm['是否服务专用配件'] = df_merged_mbom_plm['子项物料编码'].map(dict(zip(df_filter1['物料编码'], df_filter1['是否服务专用配件'])))
df_merged_mbom_plm['是否虚拟物料'] = df_merged_mbom_plm['子项物料编码'].map(dict(zip(df_filter1['物料编码'], df_filter1['是否虚拟物料'])))
print(len(df_merged_mbom_plm))
# 剔除掉虚拟物料和服务专用配件
df_merged_mbom_plm = df_merged_mbom_plm[(df_merged_mbom_plm['是否服务专用配件']!='X') & (df_merged_mbom_plm['是否虚拟物料']!='X')].reset_index(drop=True)
print(len(df_merged_mbom_plm))
# 剔除图号结尾是-0001，-0002，-0003...-0009,到-0099的物料
df_merged_mbom_plm = df_merged_mbom_plm[~df_merged_mbom_plm['图号'].str.contains(r'-00\d{2}$', na=False)]
print(len(df_merged_mbom_plm))

648742
629275
617441

In [90]:
# df_merged_mbom_plm[df_merged_mbom_plm['零件系列'].str.contains('手紧螺母')]['子项物料编码'].value_counts()

In [77]:
# 剔除工艺中间件、散装物料、关键字剔除
# 剔除零件族种包含标贴、说明书、信息码、接线图、附件、插页、铭牌、包装图、公用、标识、共用、手册、操作指引、操作说明、菜谱、印刷品
df_merged_mbom_plm = df_merged_mbom_plm[~df_merged_mbom_plm['零件系列'].str.contains('印刷品|壳体组件-消毒柜|钣金组件-消毒柜', na=False)].reset_index(drop=True)
df_merged_mbom_plm
print(len(df_merged_mbom_plm))
df_merged_mbom_plm
# df_merged_mbom_plm['国内/海外'].value_counts()

571127

,最终父项物料编码,子项物料编码,物料号,标准型号,国内/海外,产品组,产品状态,零件系列,物料组描述,物料描述,图号,是否服务专用配件,是否虚拟物料
0,1001000500258,110100051870A,1001000500258,JQ26TA,国内,吸油烟机,停止发货,装饰罩-吸油烟机-结构4TMGY,整机油烟机JQ系列,装饰罩组件(JQ26TA),0-FABQ-M800,NaN,NaN
1,1001000500373,110100051870A,1001000500373,JQ31A,国内,吸油烟机,量产,装饰罩-吸油烟机-结构4TMGY,整机油烟机JQ系列,装饰罩组件(JQ26TA),0-FABQ-M800,NaN,NaN
2,1001000500379,110100051870A,1001000500379,JQ35A,国内,吸油烟机,停止销售,装饰罩-吸油烟机-结构4TMGY,整机油烟机JQ系列,装饰罩组件(JQ26TA),0-FABQ-M800,NaN,NaN
3,1001000500384,1101000532650,1001000500384,NaN,海外,吸油烟机,量产,箱体-吸油烟机-结构2TMG,整机油烟机JQ系列,箱体部件_JQG9009X-K-PKWE,HHVM-A1000,NaN,NaN
4,1001000500384,1101000532690,1001000500384,NaN,海外,吸油烟机,量产,金属面板-吸油烟机-结构5TMG,整机油烟机JQ系列,面板部件_JQG9009X-K-PKWE,HHVM-A2000,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
571122,1013000800009,1113000803090,1013000800009,YCZ-JT1500-02-X20Max,国内,家用净水机,量产,散热片-净水机,整机净水机嵌入式净饮系列,下散热片_YCZ-JT1500-02-X20Max,JADY-A1435,NaN,NaN
571123,1013000800009,1113000803330,1013000800009,YCZ-JT1500-02-X20Max,国内,家用净水机,量产,散热片-净水机,整机净水机嵌入式净饮系列,上散热片_YCZ-JT1500-02-X20Max,JADY-A1434,NaN,NaN
571124,1013000800009,1113000803320,1013000800009,YCZ-JT1500-02-X20Max,国内,家用净水机,量产,散热水箱盖-净水机,整机净水机嵌入式净饮系列,散热水箱盖_YCZ-JT1500-02-X20Max,JADY-A1433,NaN,NaN
571125,1013000800009,1113000803060,1013000800009,YCZ-JT1500-02-X20Max,国内,家用净水机,量产,散热水箱-净水机,整机净水机嵌入式净饮系列,散热水箱_YCZ-JT1500-02-X20Max,JADY-A1432,NaN,NaN
571126,1013000800009,1113000803100,1013000800009,YCZ-JT1500-02-X20Max,国内,家用净水机,量产,水箱温度探针-净水机,整机净水机嵌入式净饮系列,水箱温度探针_YCZ-JT1500-02-X20Max,JADY-J1406,NaN,NaN

### 总的零件通用化

#### 筛选生产过的整机

In [78]:
# 筛选出有过生产的整机相关数据
worked_set = set(df_work_list['物料编码'])
df_mbom_worked = df_merged_mbom_plm[df_merged_mbom_plm['最终父项物料编码'].isin(worked_set)].reset_index(drop=True)
# 保留最终父和子，并去重
df_mbom_worked = df_mbom_worked[['最终父项物料编码','子项物料编码','标准型号','产品组','国内/海外']].drop_duplicates().reset_index(drop=True)

#### 整机的筛选（标准型号）

In [79]:
# 每个标准型号只保留最老的产品数据
stand_old_data  = df_mbom_worked.groupby('标准型号',as_index=False).agg(
                                                        最终父项物料编码  = ('最终父项物料编码', 'min')            
)
stand_old_data

# 对于每个标准型号只保留最老的产品数据
df_calu1 = df_mbom_worked[df_mbom_worked['最终父项物料编码'].isin(stand_old_data['最终父项物料编码'])].reset_index(drop=True)
df_calu1['产品组'].value_counts()
df_calu1
print(len(df_calu1))
# 剔除海外的物料
df_calu1 = df_calu1[df_calu1['国内/海外']=='国内']
df_calu1
print(len(df_calu1))

93388
82281

In [80]:
df_calu1['产品集合'] = df_calu1['产品组'].map(productgroupsset_map_1)
df_calu1

,最终父项物料编码,子项物料编码,标准型号,产品组,国内/海外,产品集合
0,1018000500008,1118000502010,JBCD13E-W5,嵌入式洗碗机,国内,嵌入式洗碗机
1,1018000500008,1118000300130,JBCD13E-W5,嵌入式洗碗机,国内,嵌入式洗碗机
2,1018000500008,1118000300730,JBCD13E-W5,嵌入式洗碗机,国内,嵌入式洗碗机
3,1001000200087,110100020524A,EA06,吸油烟机,国内,吸油烟机
4,1001000200087,110100020579D,EA06,吸油烟机,国内,吸油烟机
...,...,...,...,...,...,...
93383,1013000800009,1113000803090,YCZ-JT1500-02-X20Max,家用净水机,国内,家用净水机
93384,1013000800009,1113000803330,YCZ-JT1500-02-X20Max,家用净水机,国内,家用净水机
93385,1013000800009,1113000803320,YCZ-JT1500-02-X20Max,家用净水机,国内,家用净水机
93386,1013000800009,1113000803060,YCZ-JT1500-02-X20Max,家用净水机,国内,家用净水机
93387,1013000800009,1113000803100,YCZ-JT1500-02-X20Max,家用净水机,国内,家用净水机

In [81]:
df_calu1.to_excel(fr"D:\000物料报表\通用化报告\{month}\明细表-整机和零件（整机和零件都进行了筛选）.xlsx",index=False)

In [83]:
# 统计每个产品组内部，各个零部件的共同型号数
df_result1 = df_calu1.groupby(['产品集合','子项物料编码'],as_index=False).agg(
                                                        零件共用型号数=('最终父项物料编码','nunique'),
                                                        零件归属型号=('最终父项物料编码',lambda x: list(x.unique()))
)
df_result1.to_excel(fr"D:\000物料报表\通用化报告\{month}\零部件共用型号统计.xlsx",index=False)
df_result1

,产品集合,子项物料编码,零件共用型号数,零件归属型号
0,吸油烟机,110100010040E,3,"[1001000300073, 1001000500073, 1001000600030]"
1,吸油烟机,110100010042A,1,[1001000300073]
2,吸油烟机,110100010046A,1,[1001000300073]
3,吸油烟机,1101000100480,1,[1001001500123]
4,吸油烟机,110100010049A,1,[1001001500123]
...,...,...,...,...
17485,蒸烤微合计,1109002200640,1,[1009002200000]
17486,蒸烤微合计,1109002200650,1,[1009002200000]
17487,蒸烤微合计,1109002200670,1,[1009002200000]
17488,蒸烤微合计,1109002200760,1,[1009002200000]
17489,蒸烤微合计,1118000303520,7,"[1009000600025, 1009000600026, 1009000600030, ..."

In [88]:
df_result2 = df_result1.groupby(['产品集合'],as_index=False).agg(
                                                        通用化零件数=('零件共用型号数',lambda x: x[x>1].count()),
                                                        通用2次以上的零件数=('零件共用型号数',lambda x: x[x>=2].count()),
                                                        通用4次以上的零件数=('零件共用型号数',lambda x: x[x>=4].count()),
                                                        通用6次以上的零件数=('零件共用型号数',lambda x: x[x>=6].count()),
                                                        通用8次以上的零件数=('零件共用型号数',lambda x: x[x>=8].count()),
                                                        零件涉及产品型号数 = ('零件归属型号',lambda x: len(set().union(*x))),
                                                        零部件数=('子项物料编码','nunique')
)
df_result2['通用化零件数占比'] = df_result2['通用化零件数']/df_result2['零部件数']
productset_sort = {'吸油烟机':0,
                    '灶具':1,
                    '蒸烤微合计':2,
                    '灶集成':3,
                    '消毒柜':4,
                    '热水器':5,
                    '水槽洗碗机':6,
                    '嵌入式洗碗机':7,
                    '家用净水机':8}
df_result2.sort_values(by='产品集合',key=lambda x: x.map(productset_sort),inplace=True)
df_result2 = df_result2.reset_index(drop=True)
df_result2

,产品集合,通用化零件数,通用2次以上的零件数,通用4次以上的零件数,通用6次以上的零件数,通用8次以上的零件数,零件涉及产品型号数,零部件数,通用化零件数占比
0,吸油烟机,1663,1663,792,454,331,157,3922,0.424018
1,灶具,887,887,417,281,199,105,1946,0.455807
2,蒸烤微合计,1403,1403,822,434,285,64,2518,0.557188
3,灶集成,1207,1207,524,292,186,28,1850,0.652432
4,消毒柜,509,509,245,166,75,35,952,0.534664
5,热水器,971,971,508,407,260,67,1497,0.648631
6,水槽洗碗机,1209,1209,727,574,494,78,1722,0.702091
7,嵌入式洗碗机,1312,1312,902,742,563,71,1746,0.751432
8,家用净水机,703,703,290,142,84,25,1337,0.525804

In [89]:
df_result2.to_excel(fr"D:\000物料报表\通用化报告\{month}\通用化统计报告.xlsx",index=False)

### 平台物料+专项管控物料

In [47]:
df_plant = pd.read_excel(fr"D:\000物料报表\通用化报告\202512\烟机平台物料+专项管控物料.xlsx")
df_plant
plant_list = list(df_plant['管控零件族简称'])
plant_list

['蜗壳',
 '叶轮',
 '电机',
 '风机架',
 '电机支架',
 '进风口圈',
 '吸音盒',
 '吸音棉',
 '出风罩',
 '密封垫',
 '手紧螺母',
 '风机盖',
 '包装袋',
 '装饰罩挂钩',
 '整机垫脚',
 '电器盒',
 'LED灯',
 '油杯',
 '铝箔出风管',
 'WiFi模块',
 '整机挂钩',
 '电源线',
 '集烟罩',
 '顶后板']

In [22]:
# df_calu2 = df_merged_mbom_plm[df_merged_mbom_plm['国内/海外']=='国内'].reset_index(drop=True).copy()
# df_calu2
# df_calu2 = df_calu2[df_calu2['最终父项物料编码'].isin(worked_set)].reset_index(drop=True)
# print(df_calu2[df_calu2['零件系列'].str.contains('手紧螺母')]['子项物料编码'].value_counts())

In [51]:
# 这里是全量的国内、吸油烟机、有过生产
df_calu2 = df_merged_mbom_plm[(df_merged_mbom_plm['国内/海外']=='国内')
                            & (df_merged_mbom_plm['产品组']=='吸油烟机')
                            & (df_merged_mbom_plm['最终父项物料编码'].isin(worked_set))
                            ].reset_index(drop=True).copy()

df_calu2

,最终父项物料编码,子项物料编码,物料号,标准型号,国内/海外,产品组,产品状态,零件系列,物料组描述,物料描述,图号,是否服务专用配件,是否虚拟物料
0,1001000200087,110100020524A,1001000200087,EA06,国内,吸油烟机,量产,油杯-吸油烟机-结构4TMGY,整机油烟机EA系列,油杯组件(EA06),0-FMA-A180,NaN,NaN
1,1001000200087,110100020579D,1001000200087,EA06,国内,吸油烟机,量产,导烟板-吸油烟机-结构2TMG,整机油烟机EA系列,导烟板(EA06),0-FMA-A007,NaN,NaN
2,1001000200087,110100091511C,1001000200087,EA06,国内,吸油烟机,量产,出风罩-吸油烟机-风机TMGY,整机油烟机EA系列,出风罩组件(EM16T),0-FAAF-M100,NaN,NaN
3,1001000200087,110100010281A,1001000200087,EA06,国内,吸油烟机,量产,螺钉组合件-标准件,整机油烟机EA系列,电机减震垫螺钉组合件(CXW-189-D5G4),1-FAV-F200,NaN,NaN
4,1001000300073,1101000103340,1001000300073,JX17S,国内,吸油烟机,停止生产,底座-吸油烟机-结构5TMG,整机油烟机JX系列,螺钉座(CXW-189-D5BH),1-FAX-A009,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
22130,1001003300014,110100330034A,1001003300014,L1,国内,吸油烟机,量产,加强板-吸油烟机-结构6TMG,整机油烟机7字型系列,加强板_K1,FATA-A2106,NaN,NaN
22131,1001003300008,1101003300810,1001003300008,L1,国内,吸油烟机,停止销售,箱体右侧板-吸油烟机-结构2TMG,整机油烟机7字型系列,箱体右侧板_K1S,FATR-A2104,NaN,NaN
22132,1001003300014,1101003300810,1001003300014,L1,国内,吸油烟机,量产,箱体右侧板-吸油烟机-结构2TMG,整机油烟机7字型系列,箱体右侧板_K1S,FATR-A2104,NaN,NaN
22133,1001003300008,1101003300820,1001003300008,L1,国内,吸油烟机,停止销售,密封罩-吸油烟机-结构5TMG,整机油烟机7字型系列,密封罩_K1S,FATR-A1604,NaN,NaN
22134,1001003300014,1101003300820,1001003300014,L1,国内,吸油烟机,量产,密封罩-吸油烟机-结构5TMG,整机油烟机7字型系列,密封罩_K1S,FATR-A1604,NaN,NaN

In [52]:
df_merged_mbom_plm[df_merged_mbom_plm['零件系列'].str.contains('手紧螺母')]['子项物料编码'].value_counts()
df_calu2[df_calu2['零件系列'].str.contains('手紧螺母')]['子项物料编码'].value_counts()

子项物料编码
1101000913630    10
Name: count, dtype: int64

In [53]:
df_calu2['管控零件族简称'] = [[] for _ in range(len(df_calu2))]
df_calu2

,最终父项物料编码,子项物料编码,物料号,标准型号,国内/海外,产品组,产品状态,零件系列,物料组描述,物料描述,图号,是否服务专用配件,是否虚拟物料,管控零件族简称
0,1001000200087,110100020524A,1001000200087,EA06,国内,吸油烟机,量产,油杯-吸油烟机-结构4TMGY,整机油烟机EA系列,油杯组件(EA06),0-FMA-A180,NaN,NaN,[]
1,1001000200087,110100020579D,1001000200087,EA06,国内,吸油烟机,量产,导烟板-吸油烟机-结构2TMG,整机油烟机EA系列,导烟板(EA06),0-FMA-A007,NaN,NaN,[]
2,1001000200087,110100091511C,1001000200087,EA06,国内,吸油烟机,量产,出风罩-吸油烟机-风机TMGY,整机油烟机EA系列,出风罩组件(EM16T),0-FAAF-M100,NaN,NaN,[]
3,1001000200087,110100010281A,1001000200087,EA06,国内,吸油烟机,量产,螺钉组合件-标准件,整机油烟机EA系列,电机减震垫螺钉组合件(CXW-189-D5G4),1-FAV-F200,NaN,NaN,[]
4,1001000300073,1101000103340,1001000300073,JX17S,国内,吸油烟机,停止生产,底座-吸油烟机-结构5TMG,整机油烟机JX系列,螺钉座(CXW-189-D5BH),1-FAX-A009,NaN,NaN,[]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22130,1001003300014,110100330034A,1001003300014,L1,国内,吸油烟机,量产,加强板-吸油烟机-结构6TMG,整机油烟机7字型系列,加强板_K1,FATA-A2106,NaN,NaN,[]
22131,1001003300008,1101003300810,1001003300008,L1,国内,吸油烟机,停止销售,箱体右侧板-吸油烟机-结构2TMG,整机油烟机7字型系列,箱体右侧板_K1S,FATR-A2104,NaN,NaN,[]
22132,1001003300014,1101003300810,1001003300014,L1,国内,吸油烟机,量产,箱体右侧板-吸油烟机-结构2TMG,整机油烟机7字型系列,箱体右侧板_K1S,FATR-A2104,NaN,NaN,[]
22133,1001003300008,1101003300820,1001003300008,L1,国内,吸油烟机,停止销售,密封罩-吸油烟机-结构5TMG,整机油烟机7字型系列,密封罩_K1S,FATR-A1604,NaN,NaN,[]
22134,1001003300014,1101003300820,1001003300014,L1,国内,吸油烟机,量产,密封罩-吸油烟机-结构5TMG,整机油烟机7字型系列,密封罩_K1S,FATR-A1604,NaN,NaN,[]

In [54]:
for index,row in df_calu2.iterrows():
    for plant in plant_list:
        if plant in row['零件系列']:
            df_calu2.loc[index,'管控零件族简称'].append(plant)
df_calu2 = df_calu2[df_calu2['管控零件族简称'].notnull()]
# temp1 = df_calu2['管控零件族简称'].value_counts().to_dict()
df_calu2[df_calu2['管控零件族简称'].str.len() > 1]['管控零件族简称'].value_counts()

管控零件族简称
[电机, 电机支架]    285
[蜗壳, 吸音棉]      23
[蜗壳, 吸音盒]      22
[出风罩, 密封垫]     22
[蜗壳, 密封垫]       7
[吸音棉, 风机盖]      2
Name: count, dtype: int64

In [55]:
df_calu2 = df_calu2[df_calu2['管控零件族简称'].str.len() >= 1].reset_index(drop=True)
df_calu2

,最终父项物料编码,子项物料编码,物料号,标准型号,国内/海外,产品组,产品状态,零件系列,物料组描述,物料描述,图号,是否服务专用配件,是否虚拟物料,管控零件族简称
0,1001000200087,110100020524A,1001000200087,EA06,国内,吸油烟机,量产,油杯-吸油烟机-结构4TMGY,整机油烟机EA系列,油杯组件(EA06),0-FMA-A180,NaN,NaN,[油杯]
1,1001000200087,110100091511C,1001000200087,EA06,国内,吸油烟机,量产,出风罩-吸油烟机-风机TMGY,整机油烟机EA系列,出风罩组件(EM16T),0-FAAF-M100,NaN,NaN,[出风罩]
2,1001000300073,1101000304190,1001000300073,JX17S,国内,吸油烟机,停止生产,油杯塞-吸油烟机-结构4TMG,整机油烟机JX系列,油杯塞(CXW-189-JX07),1-FFA-A303,NaN,NaN,[油杯]
3,1001000300073,110100050307B,1001000300073,JX17S,国内,吸油烟机,停止生产,整机挂钩-吸油烟机-结构4TMGY,整机油烟机JX系列,挂钩(CXW-200-JQ01T(不带罩)),1-FHJ-M001,NaN,NaN,[整机挂钩]
4,1001000300073,1104000100010,1001000300073,JX17S,国内,吸油烟机,停止生产,包装袋-包装,整机油烟机JX系列,使用说明书包装袋(JSG32-0301-12T),1-CRA-N007,NaN,NaN,[包装袋]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8285,1001003300007,1101003300190,1001003300007,K1,国内,吸油烟机,量产,集烟罩-吸油烟机-结构2TMG,整机油烟机7字型系列,集烟罩_K1,FATA-A2102,NaN,NaN,[集烟罩]
8286,1001003300008,1101003300060,1001003300008,L1,国内,吸油烟机,停止销售,顶后板-吸油烟机-结构2TMGY,整机油烟机7字型系列,顶后板_K1,FATA-A2101,NaN,NaN,[顶后板]
8287,1001003300014,1101003300060,1001003300014,L1,国内,吸油烟机,量产,顶后板-吸油烟机-结构2TMGY,整机油烟机7字型系列,顶后板_K1,FATA-A2101,NaN,NaN,[顶后板]
8288,1001003300008,1101003300190,1001003300008,L1,国内,吸油烟机,停止销售,集烟罩-吸油烟机-结构2TMG,整机油烟机7字型系列,集烟罩_K1,FATA-A2102,NaN,NaN,[集烟罩]
8289,1001003300014,1101003300190,1001003300014,L1,国内,吸油烟机,量产,集烟罩-吸油烟机-结构2TMG,整机油烟机7字型系列,集烟罩_K1,FATA-A2102,NaN,NaN,[集烟罩]

In [56]:
def mlutone(li):
    if set(li) == {'电机', '电机支架'} :
        return '电机支架'
    elif set(li) == {'出风罩', '密封垫'} :
        return '密封垫'
    elif set(li) == {'蜗壳', '吸音棉'} :
        return '吸音棉'
    elif set(li) == {'蜗壳', '吸音盒'}  :
        return '吸音盒'
    elif set(li) == {'蜗壳', '密封垫'} :
        return '密封垫'
    elif set(li) == {'吸音棉', '风机盖'} :
        return '吸音棉'
    else:
        return li[0] if len(li) == 1 else li

In [57]:
df_calu2['管控零件族简称'] = df_calu2['管控零件族简称'].apply(lambda x: mlutone(x))
df_calu2

,最终父项物料编码,子项物料编码,物料号,标准型号,国内/海外,产品组,产品状态,零件系列,物料组描述,物料描述,图号,是否服务专用配件,是否虚拟物料,管控零件族简称
0,1001000200087,110100020524A,1001000200087,EA06,国内,吸油烟机,量产,油杯-吸油烟机-结构4TMGY,整机油烟机EA系列,油杯组件(EA06),0-FMA-A180,NaN,NaN,油杯
1,1001000200087,110100091511C,1001000200087,EA06,国内,吸油烟机,量产,出风罩-吸油烟机-风机TMGY,整机油烟机EA系列,出风罩组件(EM16T),0-FAAF-M100,NaN,NaN,出风罩
2,1001000300073,1101000304190,1001000300073,JX17S,国内,吸油烟机,停止生产,油杯塞-吸油烟机-结构4TMG,整机油烟机JX系列,油杯塞(CXW-189-JX07),1-FFA-A303,NaN,NaN,油杯
3,1001000300073,110100050307B,1001000300073,JX17S,国内,吸油烟机,停止生产,整机挂钩-吸油烟机-结构4TMGY,整机油烟机JX系列,挂钩(CXW-200-JQ01T(不带罩)),1-FHJ-M001,NaN,NaN,整机挂钩
4,1001000300073,1104000100010,1001000300073,JX17S,国内,吸油烟机,停止生产,包装袋-包装,整机油烟机JX系列,使用说明书包装袋(JSG32-0301-12T),1-CRA-N007,NaN,NaN,包装袋
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8285,1001003300007,1101003300190,1001003300007,K1,国内,吸油烟机,量产,集烟罩-吸油烟机-结构2TMG,整机油烟机7字型系列,集烟罩_K1,FATA-A2102,NaN,NaN,集烟罩
8286,1001003300008,1101003300060,1001003300008,L1,国内,吸油烟机,停止销售,顶后板-吸油烟机-结构2TMGY,整机油烟机7字型系列,顶后板_K1,FATA-A2101,NaN,NaN,顶后板
8287,1001003300014,1101003300060,1001003300014,L1,国内,吸油烟机,量产,顶后板-吸油烟机-结构2TMGY,整机油烟机7字型系列,顶后板_K1,FATA-A2101,NaN,NaN,顶后板
8288,1001003300008,1101003300190,1001003300008,L1,国内,吸油烟机,停止销售,集烟罩-吸油烟机-结构2TMG,整机油烟机7字型系列,集烟罩_K1,FATA-A2102,NaN,NaN,集烟罩
8289,1001003300014,1101003300190,1001003300014,L1,国内,吸油烟机,量产,集烟罩-吸油烟机-结构2TMG,整机油烟机7字型系列,集烟罩_K1,FATA-A2102,NaN,NaN,集烟罩

In [58]:
df_result3 = df_calu2.groupby(['管控零件族简称','子项物料编码'],as_index=False).agg(
                                                                零件共用型号数=('最终父项物料编码', 'nunique'),
                                                                零件归属型号 = ('最终父项物料编码', lambda x: list(x.unique())),
                                                                零件共用物料组数 = ('物料组描述', 'nunique'),
                                                                零件共用物料组 = ('物料组描述', lambda x: list(x.unique()))
)
df_result3

,管控零件族简称,子项物料编码,零件共用型号数,零件归属型号,零件共用物料组数,零件共用物料组
0,LED灯,110100052199C,1,[1001000500073],1,[整机油烟机JQ系列]
1,LED灯,110100052263E,22,"[1001000500412, 1001000500414, 1001000500418, ...",2,"[整机油烟机JQ系列, 整机油烟机JC系列]"
2,LED灯,110100052940D,2,"[1001002500012, 1001002500014]",1,[整机油烟机P系列]
3,LED灯,110100053131D,11,"[1001000500359, 1001000500372, 1001000500375, ...",3,"[整机油烟机JQ系列, 整机油烟机JC系列, 整机油烟机Z系列]"
4,LED灯,110100053146A,1,[1001000500359],1,[整机油烟机JQ系列]
...,...,...,...,...,...,...
972,风机盖,110100280105A,1,[1001002800001],1,[整机油烟机X20系列]
973,风机盖,1101002804870,1,[1001002800007],1,[整机油烟机X20系列]
974,风机盖,1101003300160,9,"[1001003300000, 1001003300001, 1001003300007, ...",1,[整机油烟机7字型系列]
975,风机盖,110100330251A,2,"[1001003300016, 1001003300033]",1,[整机油烟机7字型系列]
976,风机盖,110100330260A,4,"[1001003300015, 1001003300017, 1001003300018, ...",1,[整机油烟机7字型系列]

In [61]:
df_result4 = df_result3.groupby('管控零件族简称',as_index=False).agg(
                                                        通用化零件数=('零件共用型号数',lambda x: x[x>1].count()),
                                                        通用2次以上的零件数=('零件共用型号数',lambda x: x[x>=2].count()),
                                                        通用3次以上的零件数=('零件共用型号数',lambda x: x[x>=3].count()),
                                                        通用4次以上的零件数=('零件共用型号数',lambda x: x[x>=4].count()),
                                                        通用5次以上的零件数=('零件共用型号数',lambda x: x[x>=5].count()),
                                                        通用6次以上的零件数=('零件共用型号数',lambda x: x[x>=6].count()),
                                                        零部件数=('子项物料编码','nunique'),
                                                        涉及的型号数=('零件归属型号',lambda x: len(set().union(*x))),
).reset_index(drop=True)
df_result4.to_excel(fr"D:\000物料报表\通用化报告\{month}\通用化统计报告-零件族-油烟机-产品型号.xlsx",index=False)
df_result4

,管控零件族简称,通用化零件数,通用2次以上的零件数,通用3次以上的零件数,通用4次以上的零件数,通用5次以上的零件数,通用6次以上的零件数,零部件数,涉及的型号数
0,LED灯,25,25,17,15,13,13,37,240
1,WiFi模块,9,9,7,7,5,5,18,65
2,出风罩,20,20,13,13,10,10,35,245
3,包装袋,9,9,8,5,4,4,11,224
4,叶轮,29,29,17,15,14,14,42,245
5,吸音棉,30,30,23,20,20,17,48,148
6,吸音盒,28,28,24,22,17,15,42,132
7,密封垫,19,19,12,10,8,8,33,245
8,手紧螺母,1,1,1,1,1,1,1,10
9,整机垫脚,3,3,3,3,2,2,3,240
10,整机挂钩,16,16,16,12,12,10,17,244
11,油杯,87,87,61,46,41,34,148,245
12,电器盒,13,13,13,11,10,10,20,242
13,电机,40,40,27,23,19,16,54,245
14,电机支架,12,12,7,7,6,6,28,184
15,电源线,6,6,4,4,4,4,9,245
16,蜗壳,55,55,43,41,36,36,98,245
17,装饰罩挂钩,9,9,8,8,8,4,11,57
18,进风口圈,10,10,6,5,5,5,20,191
19,铝箔出风管,5,5,5,5,4,4,8,245
20,集烟罩,44,44,20,11,11,7,119,111
21,顶后板,27,27,21,17,10,8,47,103
22,风机架,56,56,35,30,24,18,91,206
23,风机盖,20,20,16,16,13,10,37,182

In [63]:
df_result5 = df_result3.groupby('管控零件族简称',as_index=False).agg(
                                                        系列通用化零件数=('零件共用物料组数',lambda x: x[x>1].count()),
                                                        通用2个系列以上的零件数=('零件共用物料组数',lambda x: x[x>=2].count()),
                                                        通用3个系列以上的零件数=('零件共用物料组数',lambda x: x[x>=3].count()),
                                                        通用4个系列以上的零件数=('零件共用物料组数',lambda x: x[x>=4].count()),
                                                        零部件数=('子项物料编码','nunique'),
                                                        涉及的系列数=('零件共用物料组',lambda x: len(set().union(*x))),
                                                        涉及的系列名=('零件共用物料组',lambda x: ','.join(set().union(*x)))
).reset_index(drop=True)
df_result5.to_excel(fr"D:\000物料报表\通用化报告\{month}\通用化统计报告-零件族-油烟机-物料组.xlsx",index=False)
df_result5

,管控零件族简称,系列通用化零件数,通用2个系列以上的零件数,通用3个系列以上的零件数,通用4个系列以上的零件数,零部件数,涉及的系列数,涉及的系列名
0,LED灯,12,12,6,2,37,15,"整机油烟机EH系列,整机油烟机J系列,整机油烟机X系列,整机油烟机SY系列,整机油烟机EN系..."
1,WiFi模块,7,7,4,4,18,10,"整机油烟机J系列,整机油烟机X20系列,整机油烟机T系列,整机油烟机Z系列,整机油烟机EM系..."
2,出风罩,12,12,6,5,35,17,"整机油烟机J系列,整机油烟机JX系列,整机油烟机X系列,整机油烟机EA系列,整机油烟机SY系..."
3,包装袋,5,5,3,3,11,17,"整机油烟机EH系列,整机油烟机JX系列,整机油烟机J系列,整机油烟机EA系列,整机油烟机SY..."
4,叶轮,20,20,9,7,42,17,"整机油烟机J系列,整机油烟机JX系列,整机油烟机X系列,整机油烟机EA系列,整机油烟机SY系..."
5,吸音棉,18,18,9,9,48,14,"整机油烟机J系列,整机油烟机EA系列,整机油烟机EG系列,整机油烟机X20系列,整机油烟机T..."
6,吸音盒,19,19,12,8,42,13,"整机油烟机J系列,整机油烟机X系列,整机油烟机EA系列,整机油烟机X20系列,整机油烟机Z系..."
7,密封垫,9,9,4,3,33,17,"整机油烟机J系列,整机油烟机JX系列,整机油烟机X系列,整机油烟机EA系列,整机油烟机SY系..."
8,手紧螺母,1,1,1,1,1,6,"整机油烟机J系列,整机油烟机EA系列,整机油烟机Z系列,整机油烟机JQ系列,整机油烟机EM系..."
9,整机垫脚,3,3,3,1,3,16,"整机油烟机J系列,整机油烟机JX系列,整机油烟机X系列,整机油烟机SY系列,整机油烟机EN系..."
10,整机挂钩,9,9,7,5,17,16,"整机油烟机J系列,整机油烟机JX系列,整机油烟机X系列,整机油烟机SY系列,整机油烟机EN系..."
11,油杯,18,18,5,5,148,17,"整机油烟机J系列,整机油烟机JX系列,整机油烟机X系列,整机油烟机EA系列,整机油烟机SY系..."
12,电器盒,10,10,5,5,20,15,"整机油烟机J系列,整机油烟机X系列,整机油烟机EA系列,整机油烟机EN系列,整机油烟机P系列..."
13,电机,20,20,12,6,54,17,"整机油烟机J系列,整机油烟机JX系列,整机油烟机X系列,整机油烟机EA系列,整机油烟机SY系..."
14,电机支架,7,7,5,5,28,14,"整机油烟机J系列,整机油烟机X系列,整机油烟机EA系列,整机油烟机EN系列,整机油烟机X20..."
15,电源线,5,5,3,2,9,17,"整机油烟机J系列,整机油烟机JX系列,整机油烟机X系列,整机油烟机EA系列,整机油烟机SY系..."
16,蜗壳,33,33,19,16,98,17,"整机油烟机J系列,整机油烟机JX系列,整机油烟机X系列,整机油烟机EA系列,整机油烟机SY系..."
17,装饰罩挂钩,6,6,3,3,11,6,"整机油烟机X系列,整机油烟机EN系列,整机油烟机X20系列,整机油烟机EM系列,整机油烟机E..."
18,进风口圈,5,5,3,3,20,17,"整机油烟机J系列,整机油烟机JX系列,整机油烟机X系列,整机油烟机EA系列,整机油烟机SY系..."
19,铝箔出风管,5,5,4,4,8,17,"整机油烟机EH系列,整机油烟机JX系列,整机油烟机J系列,整机油烟机EA系列,整机油烟机SY..."
20,集烟罩,0,0,0,0,119,8,"整机油烟机X系列,整机油烟机SY系列,整机油烟机EN系列,整机油烟机EM系列,整机油烟机EG..."
21,顶后板,3,3,0,0,47,7,"整机油烟机J系列,整机油烟机JX系列,整机油烟机Z系列,整机油烟机JQ系列,整机油烟机P系列..."
22,风机架,15,15,7,1,91,15,"整机油烟机J系列,整机油烟机X系列,整机油烟机EA系列,整机油烟机EN系列,整机油烟机X20..."
23,风机盖,8,8,6,1,37,14,"整机油烟机J系列,整机油烟机X系列,整机油烟机EA系列,整机油烟机EN系列,整机油烟机P系列..."