In [1]:
[1] + [2]

[1, 2]

In [4]:
productgroup_map={
    '油烟机': ['吸油烟机'],
    '灶具': ['灶具'],
    '蒸烤微合计': ['烤箱','蒸箱','微波炉','蒸烤烹饪机','蒸烤微烹饪机','蒸微'],
    '灶集成': ['灶消烹饪机','灶蒸烹饪机','灶蒸烤烹饪机','灶烤烹饪机'],
    '烹饪合计':['灶具','烤箱', '蒸箱', '微波炉', '蒸烤烹饪机', '蒸烤微烹饪机','蒸微','灶消烹饪机','灶蒸烹饪机','灶蒸烤烹饪机','灶烤烹饪机'],
    '水槽洗碗机': ['水槽洗碗机'],
    '嵌入式洗碗机': ['嵌入式洗碗机'],
    '洗碗机合计': ['水槽洗碗机','嵌入式洗碗机'],
    '家用净水机': ['家用净水机'],
    '热水器': ['热水器','两用炉'],
    '净热合计': ['家用净水机','热水器','两用炉'],
    '消毒柜': ['消毒柜'],
    '国内产品线合计': ['吸油烟机','灶具','烤箱','蒸箱','微波炉','蒸烤烹饪机','蒸烤微烹饪机','蒸微','灶消烹饪机','灶蒸烹饪机','灶蒸烤烹饪机','灶烤烹饪机','水槽洗碗机','嵌入式洗碗机','家用净水机','热水器','两用炉','消毒柜']
}
['消毒柜'] in productgroup_map.values()

True

In [1]:
q = {'213123':'是，且其父级未冻结、未停止生产'}
q['213123'] = '否'
print(q)

{'213123': '否'}

In [3]:
a = str(1896.4845)
b = float(a)
print(b)

1896.4845

In [1]:
import pandas as pd

df = pd.read_excel(r"C:\Users\zhangbon\Desktop\2025.08.06--物料冻结条件查询--杨亨亨\库存.xlsx")
df

,物料编码,物料描述,工厂,存储位置,仓储地点的描述,非限制使用的库存,单个编码库存小计,基本计量单位
0,1101001516530,油杯_897*33*107.5_03-Z7T,1005,2004,电器三厂喷粉车间次品仓,2,14,PC
1,1101001516530,油杯_897*33*107.5_03-Z7T,1005,2017,电器三厂自制件配送仓,12,14,PC
2,1101001516680,铰链组件_03-Z7T,1005,1001,电器三厂油烟机主料仓,40,40,PC
3,1101001517280,上挡烟板垫脚_黑色_03-Z7T,1005,1001,电器三厂油烟机主料仓,100,100,PC
4,1101001517290,下挡烟板垫脚_黑色_03-Z7T,1005,1001,电器三厂油烟机主料仓,100,100,PC
5,1101001517300,左侧板冲制件_03-Z7T,1005,2001,电器三厂冲精车间仓,5,5,PC
6,1101001517310,顶后板冲制件_03-Z7T,1005,2001,电器三厂冲精车间仓,103,103,PC
7,1101001517320,面板支撑板冲制件_03-Z7T,1005,2001,电器三厂冲精车间仓,100,100,PC
8,1101001517330,底加强板冲制件_03-Z7T,1005,2001,电器三厂冲精车间仓,122,122,PC
9,1101001517340,面板支架冲制件_03-Z7T,1005,2001,电器三厂冲精车间仓,360,360,PC
10,1101001517350,左导流板冲制件_03-Z7T,1005,2001,电器三厂冲精车间仓,253,253,PC
11,1101001517360,油杯焊接件_03-Z7T,1005,2001,电器三厂冲精车间仓,101,101,PC
12,1101001517380,右导流板冲制件_03-Z7T,1005,2001,电器三厂冲精车间仓,253,253,PC
13,1101001517390,右侧板冲制件_03-Z7T,1005,2001,电器三厂冲精车间仓,5,5,PC
14,1101001518120,油杯_灰色_897*33*107.5_03-Z7T-G,1005,2017,电器三厂自制件配送仓,4,4,PC
15,1101001518320,玻璃面板_灰色_03-Z7T-G,1005,1002,电器三厂油烟机包材仓,98,98,PC
16,1101001518690,油杯_白色_897*33*107.5_03-Z7T-W,1005,2017,电器三厂自制件配送仓,17,17,PC

In [2]:
map = {'油杯_897*33*107.5_03-Z7T':'sdasd'}

In [6]:
df['test'] = df['物料描述'].map(map).fillna('wu')
df

,物料编码,物料描述,工厂,存储位置,仓储地点的描述,非限制使用的库存,单个编码库存小计,基本计量单位,test
0,1101001516530,油杯_897*33*107.5_03-Z7T,1005,2004,电器三厂喷粉车间次品仓,2,14,PC,sdasd
1,1101001516530,油杯_897*33*107.5_03-Z7T,1005,2017,电器三厂自制件配送仓,12,14,PC,sdasd
2,1101001516680,铰链组件_03-Z7T,1005,1001,电器三厂油烟机主料仓,40,40,PC,wu
3,1101001517280,上挡烟板垫脚_黑色_03-Z7T,1005,1001,电器三厂油烟机主料仓,100,100,PC,wu
4,1101001517290,下挡烟板垫脚_黑色_03-Z7T,1005,1001,电器三厂油烟机主料仓,100,100,PC,wu
5,1101001517300,左侧板冲制件_03-Z7T,1005,2001,电器三厂冲精车间仓,5,5,PC,wu
6,1101001517310,顶后板冲制件_03-Z7T,1005,2001,电器三厂冲精车间仓,103,103,PC,wu
7,1101001517320,面板支撑板冲制件_03-Z7T,1005,2001,电器三厂冲精车间仓,100,100,PC,wu
8,1101001517330,底加强板冲制件_03-Z7T,1005,2001,电器三厂冲精车间仓,122,122,PC,wu
9,1101001517340,面板支架冲制件_03-Z7T,1005,2001,电器三厂冲精车间仓,360,360,PC,wu
10,1101001517350,左导流板冲制件_03-Z7T,1005,2001,电器三厂冲精车间仓,253,253,PC,wu
11,1101001517360,油杯焊接件_03-Z7T,1005,2001,电器三厂冲精车间仓,101,101,PC,wu
12,1101001517380,右导流板冲制件_03-Z7T,1005,2001,电器三厂冲精车间仓,253,253,PC,wu
13,1101001517390,右侧板冲制件_03-Z7T,1005,2001,电器三厂冲精车间仓,5,5,PC,wu
14,1101001518120,油杯_灰色_897*33*107.5_03-Z7T-G,1005,2017,电器三厂自制件配送仓,4,4,PC,wu
15,1101001518320,玻璃面板_灰色_03-Z7T-G,1005,1002,电器三厂油烟机包材仓,98,98,PC,wu
16,1101001518690,油杯_白色_897*33*107.5_03-Z7T-W,1005,2017,电器三厂自制件配送仓,17,17,PC,wu