In [5]:
[1] + [2]

[1, 2]

In [1]:
import pandas as pd
df1 = pd.read_excel(fr'C:\Users\zhangbon\Desktop\MDM物料基础数据-MARA-MARC(1).xlsx')

In [7]:
df2 = df1.groupby(['工厂','物料编码'],as_index=False).agg(
    数量=('物料编码','count')
)
df2[['工厂','物料编码','数量']]
df2[df2['数量']>1]

Empty DataFrame
Columns: [工厂, 物料编码, 数量]
Index: []

In [8]:
df3 = pd.read_excel(fr'C:\Users\zhangbon\Desktop\SRM系统一致性核对模版-物料20251110.xlsx')

In [9]:
df4 = df3.groupby(['工厂','物料编码'],as_index=False).agg(
    数量=('物料编码','count')
)
df4[df4['数量']>1]

Empty DataFrame
Columns: [工厂, 物料编码, 数量]
Index: []

In [4]:
productgroup_map={
    '油烟机': ['吸油烟机'],
    '灶具': ['灶具'],
    '蒸烤微合计': ['烤箱','蒸箱','微波炉','蒸烤烹饪机','蒸烤微烹饪机','蒸微'],
    '灶集成': ['灶消烹饪机','灶蒸烹饪机','灶蒸烤烹饪机','灶烤烹饪机'],
    '烹饪合计':['灶具','烤箱', '蒸箱', '微波炉', '蒸烤烹饪机', '蒸烤微烹饪机','蒸微','灶消烹饪机','灶蒸烹饪机','灶蒸烤烹饪机','灶烤烹饪机'],
    '水槽洗碗机': ['水槽洗碗机'],
    '嵌入式洗碗机': ['嵌入式洗碗机'],
    '洗碗机合计': ['水槽洗碗机','嵌入式洗碗机'],
    '家用净水机': ['家用净水机'],
    '热水器': ['热水器','两用炉'],
    '净热合计': ['家用净水机','热水器','两用炉'],
    '消毒柜': ['消毒柜'],
    '国内产品线合计': ['吸油烟机','灶具','烤箱','蒸箱','微波炉','蒸烤烹饪机','蒸烤微烹饪机','蒸微','灶消烹饪机','灶蒸烹饪机','灶蒸烤烹饪机','灶烤烹饪机','水槽洗碗机','嵌入式洗碗机','家用净水机','热水器','两用炉','消毒柜']
}
['消毒柜'] in productgroup_map.values()

True

In [1]:
q = {'213123':'是，且其父级未冻结、未停止生产'}
q['213123'] = '否'
print(q)

{'213123': '否'}

In [3]:
a = str(1896.4845)
b = float(a)
print(b)

1896.4845

In [1]:
import pandas as pd

df = pd.read_excel(r"C:\Users\zhangbon\Desktop\2025.08.06--物料冻结条件查询--杨亨亨\库存.xlsx")
df

,物料编码,物料描述,工厂,存储位置,仓储地点的描述,非限制使用的库存,单个编码库存小计,基本计量单位
0,1101001516530,油杯_897*33*107.5_03-Z7T,1005,2004,电器三厂喷粉车间次品仓,2,14,PC
1,1101001516530,油杯_897*33*107.5_03-Z7T,1005,2017,电器三厂自制件配送仓,12,14,PC
2,1101001516680,铰链组件_03-Z7T,1005,1001,电器三厂油烟机主料仓,40,40,PC
3,1101001517280,上挡烟板垫脚_黑色_03-Z7T,1005,1001,电器三厂油烟机主料仓,100,100,PC
4,1101001517290,下挡烟板垫脚_黑色_03-Z7T,1005,1001,电器三厂油烟机主料仓,100,100,PC
5,1101001517300,左侧板冲制件_03-Z7T,1005,2001,电器三厂冲精车间仓,5,5,PC
6,1101001517310,顶后板冲制件_03-Z7T,1005,2001,电器三厂冲精车间仓,103,103,PC
7,1101001517320,面板支撑板冲制件_03-Z7T,1005,2001,电器三厂冲精车间仓,100,100,PC
8,1101001517330,底加强板冲制件_03-Z7T,1005,2001,电器三厂冲精车间仓,122,122,PC
9,1101001517340,面板支架冲制件_03-Z7T,1005,2001,电器三厂冲精车间仓,360,360,PC
10,1101001517350,左导流板冲制件_03-Z7T,1005,2001,电器三厂冲精车间仓,253,253,PC
11,1101001517360,油杯焊接件_03-Z7T,1005,2001,电器三厂冲精车间仓,101,101,PC
12,1101001517380,右导流板冲制件_03-Z7T,1005,2001,电器三厂冲精车间仓,253,253,PC
13,1101001517390,右侧板冲制件_03-Z7T,1005,2001,电器三厂冲精车间仓,5,5,PC
14,1101001518120,油杯_灰色_897*33*107.5_03-Z7T-G,1005,2017,电器三厂自制件配送仓,4,4,PC
15,1101001518320,玻璃面板_灰色_03-Z7T-G,1005,1002,电器三厂油烟机包材仓,98,98,PC
16,1101001518690,油杯_白色_897*33*107.5_03-Z7T-W,1005,2017,电器三厂自制件配送仓,17,17,PC

In [2]:
map = {'油杯_897*33*107.5_03-Z7T':'sdasd'}

In [6]:
df['test'] = df['物料描述'].map(map).fillna('wu')
df

,物料编码,物料描述,工厂,存储位置,仓储地点的描述,非限制使用的库存,单个编码库存小计,基本计量单位,test
0,1101001516530,油杯_897*33*107.5_03-Z7T,1005,2004,电器三厂喷粉车间次品仓,2,14,PC,sdasd
1,1101001516530,油杯_897*33*107.5_03-Z7T,1005,2017,电器三厂自制件配送仓,12,14,PC,sdasd
2,1101001516680,铰链组件_03-Z7T,1005,1001,电器三厂油烟机主料仓,40,40,PC,wu
3,1101001517280,上挡烟板垫脚_黑色_03-Z7T,1005,1001,电器三厂油烟机主料仓,100,100,PC,wu
4,1101001517290,下挡烟板垫脚_黑色_03-Z7T,1005,1001,电器三厂油烟机主料仓,100,100,PC,wu
5,1101001517300,左侧板冲制件_03-Z7T,1005,2001,电器三厂冲精车间仓,5,5,PC,wu
6,1101001517310,顶后板冲制件_03-Z7T,1005,2001,电器三厂冲精车间仓,103,103,PC,wu
7,1101001517320,面板支撑板冲制件_03-Z7T,1005,2001,电器三厂冲精车间仓,100,100,PC,wu
8,1101001517330,底加强板冲制件_03-Z7T,1005,2001,电器三厂冲精车间仓,122,122,PC,wu
9,1101001517340,面板支架冲制件_03-Z7T,1005,2001,电器三厂冲精车间仓,360,360,PC,wu
10,1101001517350,左导流板冲制件_03-Z7T,1005,2001,电器三厂冲精车间仓,253,253,PC,wu
11,1101001517360,油杯焊接件_03-Z7T,1005,2001,电器三厂冲精车间仓,101,101,PC,wu
12,1101001517380,右导流板冲制件_03-Z7T,1005,2001,电器三厂冲精车间仓,253,253,PC,wu
13,1101001517390,右侧板冲制件_03-Z7T,1005,2001,电器三厂冲精车间仓,5,5,PC,wu
14,1101001518120,油杯_灰色_897*33*107.5_03-Z7T-G,1005,2017,电器三厂自制件配送仓,4,4,PC,wu
15,1101001518320,玻璃面板_灰色_03-Z7T-G,1005,1002,电器三厂油烟机包材仓,98,98,PC,wu
16,1101001518690,油杯_白色_897*33*107.5_03-Z7T-W,1005,2017,电器三厂自制件配送仓,17,17,PC,wu

In [21]:
import pandas as pd
df1 = pd.read_excel(r'C:\Users\zhangbon\Desktop\MDM物料工厂数据-MARC.xlsx')
df2 = pd.read_excel(r'C:\Users\zhangbon\Desktop\MDM物料基础数据-MARA.xlsx')

In [22]:
df2.columns

Index(['物料编码', '创建日期', '创建者', '上次更改', '更改者', '维护状态', '是否冻结', '物料类型', '行业部门',
       '物料组', '旧的物料编号', '基本计量单位', '订单单位', '图号', '毛重', '净重', '重量单位', '体积',
       '体积单位', '运输组', '产品组', '外包装箱长度', '外包装箱宽度', '外包装箱高度', '尺寸单位', '跨工厂物料状态',
       '普通项目类别组', '是否关键件', '工段', '是否服务配件', '是否服务专用配件', '是否易损件', '厂家1', '厂家2',
       '厂家3', '厂家4', '前一版本物料编码', '是否是新品', '呆滞期', '气源', '是否虚拟物料', '是否附件',
       '产品型号', '物料分类', '产品品类', '大系列型号', '大类', '中类', '小类', '物料等级', '是否服务虚拟件',
       '制造方式', '材料规格', '替换物料', '变更是否通用', '是否独立包装', '是否外观件', '物料版本号', '物料分类描述',
       '产品品类描述', '大类描述', '中类描述', '小类描述', '大系列型号描述', '来源系统', '替换关系', '国内/海外',
       '品牌', '是否含MAC地址', '安装类型', '产品生命周期状态', '校验码', '软件代码版本', '认证要求', '售后服务周期',
       '停止服务时间', '物料承认状态', '项目阶段', '最后生产时间', '简化型号', '产品线', '产品线描述', '产品小类',
       '产品小类描述', '智能互联', '发货地', '商品条码', '项目阶段完成时间', '协作方式', '是否滤芯', '滤芯寿命',
       '最后阶段', '化学属性', '标准型号', '是否需要销售BOM', '英文简称', '物料描述'],
      dtype='object')

In [26]:
df = pd.merge(df1, df2, left_on='物料编码', right_on='物料编码', how='left')
len(df)

812215

In [25]:
for i in range(len(df)):
    if df.loc[i, '物料编码'] != df1.loc[i, '物料编码']:
        print(i,df.loc[i, '物料编码'])
        break

In [27]:
df.to_excel(r'C:\Users\zhangbon\Desktop\MDM物料基础数据-MARA-MARC.xlsx', index=False)

In [28]:
tuple([f'-000{i}' for i in range(1,10)])

('-0001',
 '-0002',
 '-0003',
 '-0004',
 '-0005',
 '-0006',
 '-0007',
 '-0008',
 '-0009')

In [4]:
import pandas as pd
df = pd.read_excel(r'C:\Users\zhangbon\Desktop\1、PCT-物料渠道信息.xlsx')

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\zhangbon\\Desktop\\1、PCT-物料渠道信息.xlsx'

In [41]:
df = df.fillna('')
# 渠道状态拆分结果中，如果最后一个元素为空，删除
# 定义处理函数：拆分后若最后一个元素为空则删除
def clean_last_empty(lst):
    # 先过滤掉拆分后可能的空字符串（如连续分号的情况），再判断最后一个元素
    # 或仅判断最后一个元素是否为空：
    if lst and lst[-1] == "":  # 列表非空且最后一个元素为空
        return lst[:-1]
    return lst
df['渠道状态拆分结果'] = df['渠道状态'].str.split(';').apply(clean_last_empty)
df
df_exploded = df.explode('渠道状态拆分结果').reset_index(drop=True)
df_exploded

                 物料编码      渠道状态 渠道状态拆分结果
0       1001000300093  海外,停止销售;  海外,停止销售
1       1001000300079                NaN
2       1001000300081                NaN
3       1001000300082                NaN
4       1001000300089  海外,停止销售;  海外,停止销售
...               ...       ...      ...
221330  1502010602838                NaN
221331  1502010602839                NaN
221332  1502010602840                NaN
221333  1502010602841                NaN
221334  1502010602842                NaN

[221335 rows x 3 columns]

In [42]:
df_exploded = df_exploded.fillna('')
df_exploded['渠道'] = df_exploded['渠道状态拆分结果'].str.split(',').str[0].fillna('')
df_exploded['状态'] = df_exploded['渠道状态拆分结果'].str.split(',').str[1].fillna('')
df_exploded

                 物料编码      渠道状态 渠道状态拆分结果  渠道    状态
0       1001000300093  海外,停止销售;  海外,停止销售  海外  停止销售
1       1001000300079
2       1001000300081
3       1001000300082
4       1001000300089  海外,停止销售;  海外,停止销售  海外  停止销售
...               ...       ...      ...  ..   ...
221330  1502010602838
221331  1502010602839
221332  1502010602840
221333  1502010602841
221334  1502010602842

[221335 rows x 5 columns]

In [1]:
import pandas as pd

In [2]:
mara = pd.read_excel(r'C:\Users\zhangbon\Desktop\MDM物料基础数据-MARA-调整好的字段版本(1).xlsx', engine='openpyxl')

In [ ]:
mara.columns    
mara['物料编码'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 221242 entries, 0 to 221241
Series name: 物料编码
Non-Null Count   Dtype
--------------   -----
221242 non-null  object
dtypes: object(1)
memory usage: 1.7+ MB

In [ ]:
渠道 = pd.read_excel(r"C:\Users\zhangbon\Desktop\MDM物料渠道信息表.XLSX")
渠道.columns

Index(['物料编码', '渠道名称', '渠道状态', '渠道状态代码', '状态开始时间', '适用业务类型', '开始销售时间',
       '停止销售时间'],
      dtype='object')

In [13]:
渠道['物料编码'] = 渠道['物料编码'].astype(str).str.strip().str[:13]

In [14]:
mara_渠道 = pd.merge(mara,渠道,on='物料编码',how='left')
mara_渠道.to_excel(r'C:\Users\zhangbon\Desktop\mara-渠道.xlsx', index=False)

In [6]:
marc = pd.read_excel(r'C:\Users\zhangbon\Desktop\MDM物料工厂数据-MARC(1).xlsx', engine='openpyxl')

In [9]:
df0 = pd.merge(mara,marc,on='物料编码',how='left')

In [12]:
# del mara
del marc

In [13]:
df0.to_excel(r'C:\Users\zhangbon\Desktop\mara-marc合并结果.xlsx', index=False)