In [1]:
import pandas as pd
import openpyxl
from IPython.display import display
import xlsxwriter
import numpy as np
from IPython.display import display, Image, HTML

### 所需要的所有文件：
# 统计周期内产品核算价汇总
# 所有11开头的物料导出MARA
# 两个月出一次，下一次是11月

### 对照关系，每次都需要更新

In [2]:
#指定月份
month = '202512'
month_name = '12月'
year_name = '2025年'
income_year_name = '2024年发货收入'
#指定时间范围
start_date = pd.Timestamp('2025-01-01')
end_date = pd.Timestamp('2025-12-31')
#每年的物料基准数量--年度更新
productgroup_starting_map = {'油烟机':11823
, '灶具':6485
, '蒸烤微合计':6655
, '灶集成':2060
, '烹饪合计':15200
, '水槽洗碗机':4088
, '嵌入式洗碗机':2936
, '洗碗机合计':7024
, '家用净水机':2083
, '热水器':4352
, '净热合计':6435
, '消毒柜':2589
, '国内产品线合计':43071
, '海外合计':7547
}

#发货收入基准，年度更新
productgroup_sales_map = {'油烟机':760275
, '灶具':364114
, '蒸烤微合计':117582
, '灶集成':51586
, '烹饪合计':533281
, '水槽洗碗机':70840
, '嵌入式洗碗机':129987
, '洗碗机合计':200827
, '家用净水机':21298
, '热水器':50544
, '净热合计':71842
, '消毒柜':51444
, '国内产品线合计':1617669
}

target_map ={
    '油烟机': 58.5,
    '灶具': 49.52,
    '蒸烤微合计':16.29,
    '灶集成': 24.89,
    '烹饪合计':31.49,
    '水槽洗碗机': '/',
    '嵌入式洗碗机': '/',
    '洗碗机合计': 25.73,
    '家用净水机': 9.2,
    '热水器': 10.45,
    '净热合计': 10.04,
    '消毒柜': 14.5,
    '国内产品线合计': 33.8
}

beizhu = {
    '油烟机': '不含ODM、空调/IMES',
    '灶具': '不含火炬、智能灶',
    '蒸烤微合计':'含烹饪机',
    '灶集成': '不含灶消',
    '烹饪合计':'不含灶消',
    '水槽洗碗机': '/',
    '嵌入式洗碗机': '/',
    '洗碗机合计': '/',
    '家用净水机': '/',
    '热水器': '含两用炉',
    '净热合计': '/',
    '消毒柜': '/',
    '国内产品线合计': '/',
    '海外合计':'/'
}
#依据规则构造出所有的对照关系，这里是用于物料的对照

productgroup_map={
    '油烟机': ['吸油烟机'],
    '灶具': ['灶具'],
    '蒸烤微合计': ['烤箱','蒸箱','微波炉','蒸烤烹饪机','蒸烤微烹饪机','蒸微'],
    '灶集成': ['灶消烹饪机','灶蒸烹饪机','灶蒸烤烹饪机','灶烤烹饪机'],
    '烹饪合计':['灶具','烤箱', '蒸箱', '微波炉', '蒸烤烹饪机', '蒸烤微烹饪机','蒸微','灶消烹饪机','灶蒸烹饪机','灶蒸烤烹饪机','灶烤烹饪机'],
    '水槽洗碗机': ['水槽洗碗机'],
    '嵌入式洗碗机': ['嵌入式洗碗机'],
    '洗碗机合计': ['水槽洗碗机','嵌入式洗碗机'],
    '家用净水机': ['家用净水机'],
    '热水器': ['热水器','两用炉'],
    '净热合计': ['家用净水机','热水器','两用炉'],
    '消毒柜': ['消毒柜'],
    '国内产品线合计': ['吸油烟机','灶具','烤箱','蒸箱','微波炉','蒸烤烹饪机','蒸烤微烹饪机','蒸微','灶消烹饪机','灶蒸烹饪机','灶蒸烤烹饪机','灶烤烹饪机','水槽洗碗机','嵌入式洗碗机','家用净水机','热水器','两用炉','消毒柜']
}

product_dict = {
'B1':'橱柜',                
'B2':'集成家居',            
'F1':'服务产品',            
'Y1':'气电烹饪灶（智能灶）',
'Y2':'下排集成灶',          
'Y3':'集成式洗碗机',        
'Y4':'灶烤烹饪机',          
'Y5':'集成油烟机',          
'Y6':'蒸烤微集成烹饪中心',  
'Y7':'灶蒸烤微烹饪机',      
'Z1':'吸油烟机',            
'Z2':'灶具',                
'Z3':'消毒柜',              
'Z4':'微波炉',              
'Z5':'蒸箱',                
'Z6':'烤箱',                
'Z7':'热水器',              
'Z8':'水槽洗碗机',          
'Z9':'保温箱',              
'ZA':'蒸锅',                
'ZC':'橱柜',                
'ZD':'家用净水机',          
'ZE':'大厨管家',            
'ZF':'服务',                
'ZG':'空壳',                
'ZH':'料理机',              
'ZJ':'新风空净',            
'ZK':'蒸微',                
'ZL':'蒸烤烹饪机',          
'ZM':'灶蒸烤烹饪机',        
'ZN':'灶消烹饪机',          
'ZP':'灶蒸烹饪机',          
'ZQ':'蒸烤微烹饪机',        
'ZR':'商用净水机',          
'ZS':'嵌入式洗碗机',        
'ZT':'两用炉',              
'ZU':'外置循环系统',        
'ZV':'家用冰箱',            
'ZW':'家用厨余处理机',      
'ZX':'地面手持式清洁机',    
'ZY':'地面机器人清洁机',    
'ZZ':'其他',
}

### 收入数据（每次更新收入表路径，和sheet名）,由单型号中输出

In [3]:
# 物流和财务的发货收入中是包含了1012开头的样机的，PLM中是只有成品的，所以这里样机的产品组是空的，样机不在我们报告的统计范围内
sale_income = pd.read_excel(rf'D:\000物料报表\{month}\单物料产值\统计周期内产品核算价汇总.xlsx')
核算_col = '核算价'
sale_income[f'{核算_col}'] = sale_income[f'{核算_col}'].fillna(0)
sale_income = sale_income.replace('NaN',0)
sale_income_grouped = sale_income.groupby('产品组').agg({f'{核算_col}':sum}).rename(columns={f'{核算_col}':'总收入'}).reset_index()
sale_income_grouped_map = dict(zip(sale_income_grouped['产品组'],sale_income_grouped['总收入']))

productgroup2_income_map = {}
for k,v in productgroup_map.items():
    productgroup2_income_map[k] = 0
    for item in v:
        productgroup2_income_map[k] += sale_income_grouped_map.get(item,0)/10000
productgroup2_income_map

C:\Users\zhangbon\AppData\Local\Temp\ipykernel_21612\2002267409.py:6: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  sale_income_grouped = sale_income.groupby('产品组').agg({f'{核算_col}':sum}).rename(columns={f'{核算_col}':'总收入'}).reset_index()

{'油烟机': 701477.8928,
 '灶具': 356352.307,
 '蒸烤微合计': 106930.0589,
 '灶集成': 66489.355,
 '烹饪合计': 529771.7209,
 '水槽洗碗机': 78748.0245,
 '嵌入式洗碗机': 136885.049,
 '洗碗机合计': 215633.0735,
 '家用净水机': 21576.175,
 '热水器': 46095.6464,
 '净热合计': 67671.8214,
 '消毒柜': 38127.714,
 '国内产品线合计': 1552682.2226}

### 读取零部件原始数据，并开始处理

In [4]:
df = pd.read_excel(fr"D:\000物料报表\{month}\单物料产值\物料精简原始数据12月.xlsx")
df = df.astype(str)
#展示df的数据格式
df.info()
# 展示df的前五行数据
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128699 entries, 0 to 128698
Data columns (total 13 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   物料编码         128699 non-null  object
 1   创建日期         128699 non-null  object
 2   是否冻结         128699 non-null  object
 3   图号           128699 non-null  object
 4   产品组          128699 non-null  object
 5   跨工厂物料状态      128699 non-null  object
 6   是否虚拟物料       128699 non-null  object
 7   国内/海外        128699 non-null  object
 8   是否涉及认证一致性管控  128699 non-null  object
 9   整机认证地区       128699 non-null  object
 10  整机认证类型       128699 non-null  object
 11  整机海外认证标准     128699 non-null  object
 12  物料描述         128699 non-null  object
dtypes: object(13)
memory usage: 12.8+ MB

,物料编码,创建日期,是否冻结,图号,产品组,跨工厂物料状态,是否虚拟物料,国内/海外,是否涉及认证一致性管控,整机认证地区,整机认证类型,整机海外认证标准,物料描述
0,1101000100400,2018-07-10,X,1-FAA-A004,Z1,nan,nan,20.0,nan,nan,nan,nan,垫脚(CXW-128-Q2)
1,1101000100410,2018-07-10,nan,1-FAA-A106,Z1,nan,nan,20.0,nan,nan,nan,nan,线夹(CXW-128-Q2)
2,1101000100430,2018-07-10,X,1-FAA-A200,Z1,nan,nan,20.0,nan,nan,nan,nan,上导风板组件(CXW-128-Q2)
3,1101000100440,2018-07-10,X,1-FAA-A201,Z1,nan,nan,20.0,nan,nan,nan,nan,连接圈(CXW-128-Q2)
4,1101000100450,2018-07-10,X,1-FAA-A211,Z1,nan,nan,20.0,nan,nan,nan,nan,上导风板(CXW-128-Q2)

In [5]:
list_drop = []
df['删除原因'] = '空'
for i in range(len(df)):
    if 'ZD70' in df.loc[i,'物料描述']:
        list_drop.append(i)
        df.loc[i,'删除原因'] = 'ODM'
    if df.loc[i,'图号'][:4] == 'LAFS':
        list_drop.append(i)
        df.loc[i,'删除原因'] = '火炬'
    if df.loc[i,'图号'][:4] == 'LAFT':
        list_drop.append(i)
        df.loc[i,'删除原因'] = '火炬'
    if df.loc[i,'物料编码'][:8] == '11010022':
        list_drop.append(i)
        df.loc[i,'删除原因'] = 'IMES'  
    if df.loc[i,'物料编码'][:8] == '11010027':
        list_drop.append(i)
        df.loc[i,'删除原因'] = '空调油烟机'  
    if df.loc[i,'图号'][:4] == 'PACA':
        list_drop.append(i)
        df.loc[i,'删除原因'] = '净存机'
    if df.loc[i,'产品组'] == 'ZN':
        list_drop.append(i)
        df.loc[i,'删除原因'] = '灶消'

In [6]:
#依据产品组的产品组描述的对照关系，生成一列产品组描述
# 输入：字典, 产品组描述的对照关系，产品组描述的列名
df['产品组描述'] = df['产品组'].map(product_dict)
df['国内/海外'] = df['国内/海外'].apply(lambda x:'国内' if x in ['20.0','20',20] else ('海外' if x in ['10.0','10',10] else '空'))
df = df.fillna('空')
df[['是否冻结','跨工厂物料状态','是否虚拟物料','删除原因']] = df[['是否冻结','跨工厂物料状态','是否虚拟物料','删除原因']].replace('nan','空')
df

,物料编码,创建日期,是否冻结,图号,产品组,跨工厂物料状态,是否虚拟物料,国内/海外,是否涉及认证一致性管控,整机认证地区,整机认证类型,整机海外认证标准,物料描述,删除原因,产品组描述
0,1101000100400,2018-07-10,X,1-FAA-A004,Z1,空,空,国内,nan,nan,nan,nan,垫脚(CXW-128-Q2),空,吸油烟机
1,1101000100410,2018-07-10,空,1-FAA-A106,Z1,空,空,国内,nan,nan,nan,nan,线夹(CXW-128-Q2),空,吸油烟机
2,1101000100430,2018-07-10,X,1-FAA-A200,Z1,空,空,国内,nan,nan,nan,nan,上导风板组件(CXW-128-Q2),空,吸油烟机
3,1101000100440,2018-07-10,X,1-FAA-A201,Z1,空,空,国内,nan,nan,nan,nan,连接圈(CXW-128-Q2),空,吸油烟机
4,1101000100450,2018-07-10,X,1-FAA-A211,Z1,空,空,国内,nan,nan,nan,nan,上导风板(CXW-128-Q2),空,吸油烟机
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128694,112500040010A,2024-06-27,空,SAEF-A0010,F1,空,空,国内,nan,nan,nan,nan,蒸烤盘_银色_FJ-YKZP1,空,服务产品
128695,112500040018A,2024-06-25,空,SAEH-A0010,F1,空,空,国内,nan,nan,nan,nan,蒸烤盘_银色_FJ-YKZP3,空,服务产品
128696,112500060000A,2025-01-02,空,FATB-A2000,F1,空,空,国内,nan,nan,nan,nan,铝箔出风管组件_φ160_4m_BBF-B-16-AA1,空,服务产品
128697,112600010020A,2025-12-22,空,DAHE-A0002,Y8,空,空,国内,nan,nan,nan,nan,预孔样板_750*460*R10,空,空
128698,112600010023A,2026-01-04,空,DAHE-A0051,Y8,空,空,国内,nan,nan,nan,nan,移动槽盖板_JBS2T-X20,空,空

In [7]:
df.to_excel(fr"D:\000物料报表\{month}\单物料产值\物料精简原始数据处理稿.xlsx",index=False)

In [8]:
#先筛出删除原因为空的df,且非虚拟物料
df_not_del = df[(df["删除原因"] == "空")&(df["是否虚拟物料"] == "空")]
df_not_del

,物料编码,创建日期,是否冻结,图号,产品组,跨工厂物料状态,是否虚拟物料,国内/海外,是否涉及认证一致性管控,整机认证地区,整机认证类型,整机海外认证标准,物料描述,删除原因,产品组描述
0,1101000100400,2018-07-10,X,1-FAA-A004,Z1,空,空,国内,nan,nan,nan,nan,垫脚(CXW-128-Q2),空,吸油烟机
1,1101000100410,2018-07-10,空,1-FAA-A106,Z1,空,空,国内,nan,nan,nan,nan,线夹(CXW-128-Q2),空,吸油烟机
2,1101000100430,2018-07-10,X,1-FAA-A200,Z1,空,空,国内,nan,nan,nan,nan,上导风板组件(CXW-128-Q2),空,吸油烟机
3,1101000100440,2018-07-10,X,1-FAA-A201,Z1,空,空,国内,nan,nan,nan,nan,连接圈(CXW-128-Q2),空,吸油烟机
4,1101000100450,2018-07-10,X,1-FAA-A211,Z1,空,空,国内,nan,nan,nan,nan,上导风板(CXW-128-Q2),空,吸油烟机
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128694,112500040010A,2024-06-27,空,SAEF-A0010,F1,空,空,国内,nan,nan,nan,nan,蒸烤盘_银色_FJ-YKZP1,空,服务产品
128695,112500040018A,2024-06-25,空,SAEH-A0010,F1,空,空,国内,nan,nan,nan,nan,蒸烤盘_银色_FJ-YKZP3,空,服务产品
128696,112500060000A,2025-01-02,空,FATB-A2000,F1,空,空,国内,nan,nan,nan,nan,铝箔出风管组件_φ160_4m_BBF-B-16-AA1,空,服务产品
128697,112600010020A,2025-12-22,空,DAHE-A0002,Y8,空,空,国内,nan,nan,nan,nan,预孔样板_750*460*R10,空,空
128698,112600010023A,2026-01-04,空,DAHE-A0051,Y8,空,空,国内,nan,nan,nan,nan,移动槽盖板_JBS2T-X20,空,空

### 对未冻结的物料做计算处理

In [9]:
#先对未冻结的做处理
df_not_froze = df_not_del[df_not_del["是否冻结"] == "空"]
df_not_froze["创建日期"] = pd.to_datetime(df_not_froze["创建日期"])
df_not_froze

C:\Users\zhangbon\AppData\Local\Temp\ipykernel_21612\878873356.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_not_froze["创建日期"] = pd.to_datetime(df_not_froze["创建日期"])

,物料编码,创建日期,是否冻结,图号,产品组,跨工厂物料状态,是否虚拟物料,国内/海外,是否涉及认证一致性管控,整机认证地区,整机认证类型,整机海外认证标准,物料描述,删除原因,产品组描述
1,1101000100410,2018-07-10,空,1-FAA-A106,Z1,空,空,国内,nan,nan,nan,nan,线夹(CXW-128-Q2),空,吸油烟机
5,1101000100470,2018-07-10,空,1-FAA-A221,Z1,空,空,国内,nan,nan,nan,nan,网圈(CXW-128-Q2),空,吸油烟机
6,1101000100480,2018-07-10,空,1-FAA-A222,Z1,空,空,国内,nan,nan,nan,nan,网罩内圈(CXW-128-Q2),空,吸油烟机
8,1101000100510,2018-07-10,空,1-FAA-A302,Z1,空,空,国内,nan,nan,nan,nan,左灯罩(CXW-128-Q2),空,吸油烟机
9,1101000100520,2018-07-10,空,1-FAA-A303,Z1,空,空,国内,nan,nan,nan,nan,右灯罩(CXW-128-Q2),空,吸油烟机
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128694,112500040010A,2024-06-27,空,SAEF-A0010,F1,空,空,国内,nan,nan,nan,nan,蒸烤盘_银色_FJ-YKZP1,空,服务产品
128695,112500040018A,2024-06-25,空,SAEH-A0010,F1,空,空,国内,nan,nan,nan,nan,蒸烤盘_银色_FJ-YKZP3,空,服务产品
128696,112500060000A,2025-01-02,空,FATB-A2000,F1,空,空,国内,nan,nan,nan,nan,铝箔出风管组件_φ160_4m_BBF-B-16-AA1,空,服务产品
128697,112600010020A,2025-12-22,空,DAHE-A0002,Y8,空,空,国内,nan,nan,nan,nan,预孔样板_750*460*R10,空,空
128698,112600010023A,2026-01-04,空,DAHE-A0051,Y8,空,空,国内,nan,nan,nan,nan,移动槽盖板_JBS2T-X20,空,空

In [10]:
#对未冻结的国内的物料进行处理,all代表当前周期内的所有物料数，part代表的是周期内所有的新增物料数
df_not_froze_china = df_not_froze[df_not_froze["国内/海外"] == "国内"]
#对于国内的所有进行处理
df_not_froze_china_all = df_not_froze_china[df_not_froze_china['创建日期'] <= end_date ].groupby(['产品组描述']).size().reset_index(name='数量')
df_not_froze_china_part = df_not_froze_china[(df_not_froze_china['创建日期'] >= start_date ) & (df_not_froze_china['创建日期'] <= end_date )].groupby(['产品组描述']).size().reset_index(name='数量')
with pd.ExcelWriter(fr"D:\000物料报表\{month}\单物料产值\非冻结计数—国内.xlsx") as writer:
    df_not_froze_china_all.to_excel(writer, sheet_name='国内-all', index=False)
    df_not_froze_china_part.to_excel(writer, sheet_name='国内-part', index=False)
df_not_froze_china_all

         产品组描述     数量
0        下排集成灶   1636
1          两用炉    450
2          保温箱     84
3         吸油烟机  14222
4        商用净水机    739
5     地面手持式清洁机   1839
6       外置循环系统     63
7         大厨管家      1
8         家用冰箱   1686
9        家用净水机   2807
10      嵌入式洗碗机   3930
11         微波炉    607
12         料理机    274
13        新风空净    581
14        服务产品    204
15  气电烹饪灶（智能灶）    158
16       水槽洗碗机   4444
17         消毒柜   2803
18          灶具   7283
19     灶蒸烤微烹饪机    122
20      灶蒸烤烹饪机   2503
21       灶蒸烹饪机    105
22          烤箱   1355
23         热水器   4252
24           空     40
25          蒸微    463
26      蒸烤微烹饪机    898
27       蒸烤烹饪机   2606
28          蒸箱   1596
29          蒸锅     36
30      集成式洗碗机   1030

In [11]:
#对未冻结的国外的物料进行处理
df_not_froze_oversea = df_not_froze[df_not_froze["国内/海外"] == "海外"]
df_not_froze_oversea_all = df_not_froze_oversea[df_not_froze_oversea['创建日期'] <= end_date ].groupby(['产品组描述']).size().reset_index(name='数量')
df_not_froze_oversea_part = df_not_froze_oversea[(df_not_froze_oversea['创建日期'] >= start_date ) & (df_not_froze_oversea['创建日期'] <= end_date )].groupby(['产品组描述']).size().reset_index(name='数量')
with pd.ExcelWriter(fr"D:\000物料报表\{month}\单物料产值\非冻结计数—海外.xlsx") as writer:
    df_not_froze_oversea_all.to_excel(writer, sheet_name='海外-all', index=False)
    df_not_froze_oversea_part.to_excel(writer, sheet_name='海外-part', index=False)
print(f'海外物料总数量为：{sum(df_not_froze_oversea_all["数量"])}')
print(f'海外物料限定范围内数量为：{sum(df_not_froze_oversea_part["数量"])}')
print(f'海外物料总数量(去除不考核产品)为：{sum(df_not_froze_oversea_all[~(df_not_froze_oversea_all["产品组描述"]=="不考核产品")]["数量"])}')
print(f'海外物料限定范围内数量(去除不考核产品)为：{sum(df_not_froze_oversea_part[~(df_not_froze_oversea_part["产品组描述"]=="不考核产品")]["数量"])}')

海外物料总数量为：9291
海外物料限定范围内数量为：1765
海外物料总数量(去除不考核产品)为：9291
海外物料限定范围内数量(去除不考核产品)为：1765

### 对剔除掉冻结或采购冻结的物料进行处理

In [12]:
#筛选出跨工厂物料状态为空且是否冻结为空
df_not_del["创建日期"] = pd.to_datetime(df_not_del["创建日期"])
df_not_caigou_froze = df_not_del[(df_not_del['跨工厂物料状态'] == '空') & (df_not_del['是否冻结'] == "空")]
df_not_caigou_froze["创建日期"] = pd.to_datetime(df_not_caigou_froze["创建日期"])
df_not_caigou_froze

C:\Users\zhangbon\AppData\Local\Temp\ipykernel_21612\1962439926.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_not_del["创建日期"] = pd.to_datetime(df_not_del["创建日期"])
C:\Users\zhangbon\AppData\Local\Temp\ipykernel_21612\1962439926.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_not_caigou_froze["创建日期"] = pd.to_datetime(df_not_caigou_froze["创建日期"])

,物料编码,创建日期,是否冻结,图号,产品组,跨工厂物料状态,是否虚拟物料,国内/海外,是否涉及认证一致性管控,整机认证地区,整机认证类型,整机海外认证标准,物料描述,删除原因,产品组描述
1,1101000100410,2018-07-10,空,1-FAA-A106,Z1,空,空,国内,nan,nan,nan,nan,线夹(CXW-128-Q2),空,吸油烟机
5,1101000100470,2018-07-10,空,1-FAA-A221,Z1,空,空,国内,nan,nan,nan,nan,网圈(CXW-128-Q2),空,吸油烟机
6,1101000100480,2018-07-10,空,1-FAA-A222,Z1,空,空,国内,nan,nan,nan,nan,网罩内圈(CXW-128-Q2),空,吸油烟机
8,1101000100510,2018-07-10,空,1-FAA-A302,Z1,空,空,国内,nan,nan,nan,nan,左灯罩(CXW-128-Q2),空,吸油烟机
9,1101000100520,2018-07-10,空,1-FAA-A303,Z1,空,空,国内,nan,nan,nan,nan,右灯罩(CXW-128-Q2),空,吸油烟机
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128694,112500040010A,2024-06-27,空,SAEF-A0010,F1,空,空,国内,nan,nan,nan,nan,蒸烤盘_银色_FJ-YKZP1,空,服务产品
128695,112500040018A,2024-06-25,空,SAEH-A0010,F1,空,空,国内,nan,nan,nan,nan,蒸烤盘_银色_FJ-YKZP3,空,服务产品
128696,112500060000A,2025-01-02,空,FATB-A2000,F1,空,空,国内,nan,nan,nan,nan,铝箔出风管组件_φ160_4m_BBF-B-16-AA1,空,服务产品
128697,112600010020A,2025-12-22,空,DAHE-A0002,Y8,空,空,国内,nan,nan,nan,nan,预孔样板_750*460*R10,空,空
128698,112600010023A,2026-01-04,空,DAHE-A0051,Y8,空,空,国内,nan,nan,nan,nan,移动槽盖板_JBS2T-X20,空,空

In [13]:
#对非采购冻结和冻结的国内物料进行处理
df_not_caigou_froze_china = df_not_caigou_froze[df_not_caigou_froze["国内/海外"] == "国内"]
df_not_caigou_froze_china['创建日期'] = pd.to_datetime(df_not_caigou_froze_china['创建日期'])
#对于国内的进行处理
df_not_caigou_froze_china_all = df_not_caigou_froze_china[df_not_caigou_froze_china['创建日期'] <= end_date ].groupby(['产品组描述']).size().reset_index(name='数量')
df_not_caigou_froze_china_part = df_not_del[(df_not_del['创建日期'] >= start_date ) & (df_not_del['创建日期'] <= end_date )& (df_not_del['国内/海外'] == "国内")].groupby(['产品组描述']).size().reset_index(name='数量')
with pd.ExcelWriter(fr"D:\000物料报表\{month}\单物料产值\非采购非冻结计数—国内.xlsx") as writer:
    df_not_caigou_froze_china_all.to_excel(writer, sheet_name='国内-all', index=False)
    df_not_caigou_froze_china_part.to_excel(writer, sheet_name='国内-新建', index=False)
df_not_caigou_froze_china_all

#建立产品组描述和数量之间的映射关系
productgroup_all_china_map = dict(zip(df_not_caigou_froze_china_all['产品组描述'], df_not_caigou_froze_china_all['数量']))
productgroup_part_china_map = dict(zip(df_not_caigou_froze_china_part['产品组描述'], df_not_caigou_froze_china_part['数量']))
productgroup_all_china_map

C:\Users\zhangbon\AppData\Local\Temp\ipykernel_21612\2021811776.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_not_caigou_froze_china['创建日期'] = pd.to_datetime(df_not_caigou_froze_china['创建日期'])

{'下排集成灶': 1636,
 '两用炉': 447,
 '保温箱': 84,
 '吸油烟机': 12867,
 '商用净水机': 739,
 '地面手持式清洁机': 1839,
 '外置循环系统': 63,
 '大厨管家': 1,
 '家用冰箱': 1686,
 '家用净水机': 2769,
 '嵌入式洗碗机': 3930,
 '微波炉': 506,
 '料理机': 274,
 '新风空净': 581,
 '服务产品': 204,
 '气电烹饪灶（智能灶）': 158,
 '水槽洗碗机': 4444,
 '消毒柜': 2623,
 '灶具': 6762,
 '灶蒸烤微烹饪机': 122,
 '灶蒸烤烹饪机': 2275,
 '灶蒸烹饪机': 91,
 '烤箱': 1166,
 '热水器': 4196,
 '空': 40,
 '蒸微': 356,
 '蒸烤微烹饪机': 861,
 '蒸烤烹饪机': 2360,
 '蒸箱': 1248,
 '蒸锅': 36,
 '集成式洗碗机': 1030}

In [14]:
#对于海外的进行处理
df_not_caigou_froze_oversea = df_not_caigou_froze[df_not_caigou_froze["国内/海外"] == "海外"]
df_not_caigou_froze_oversea["创建日期"] = pd.to_datetime(df_not_caigou_froze_oversea['创建日期'])
#对于海外的所有进行处理
df_not_caigou_froze_oversea_all = df_not_caigou_froze_oversea[df_not_caigou_froze_oversea['创建日期'] <= end_date ].groupby(['产品组描述']).size().reset_index(name='数量')
#对于海外的限定时间期限进行处理
df_not_caigou_froze_oversea_part = df_not_del[(df_not_del['创建日期'] >= start_date ) & (df_not_del['创建日期'] <= end_date )& (df_not_del['国内/海外'] == "海外")].groupby(['产品组描述']).size().reset_index(name='数量')
with pd.ExcelWriter(fr"D:\000物料报表\{month}\单物料产值\非采购非冻结计数—海外.xlsx") as writer:
    df_not_caigou_froze_oversea_all.to_excel(writer, sheet_name='海外-all', index=False)
    df_not_caigou_froze_oversea_part.to_excel(writer, sheet_name='海外-part', index=False)
df_not_caigou_froze_oversea_all
print(f'非采购非冻结海外物料总数量为（未排除不统计的产品组数据）：{sum(df_not_caigou_froze_oversea_all["数量"])}')
print(f'非采购非冻结海外物料限定范围内数量为（未排除不统计的产品组数据）：{sum(df_not_caigou_froze_oversea_part["数量"])}')
#建立产品组描述和数量之间的映射关系
productgroup_all_oversea_map = sum(df_not_caigou_froze_oversea_all[(df_not_caigou_froze_oversea_all["产品组描述"].isin(productgroup_map['国内产品线合计']))]["数量"])
productgroup_part_oversea_map = sum(df_not_caigou_froze_oversea_part[(df_not_caigou_froze_oversea_part["产品组描述"].isin(productgroup_map['国内产品线合计']))]["数量"])
print(productgroup_all_oversea_map)
print(productgroup_part_oversea_map)

C:\Users\zhangbon\AppData\Local\Temp\ipykernel_21612\3207227662.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_not_caigou_froze_oversea["创建日期"] = pd.to_datetime(df_not_caigou_froze_oversea['创建日期'])

非采购非冻结海外物料总数量为（未排除不统计的产品组数据）：9283
非采购非冻结海外物料限定范围内数量为（未排除不统计的产品组数据）：1772
9215
1755

### 构造出产品集合，每个产品集合对应的现状物料数量和统计周期内的新增物料数量

In [15]:

# 匹配出每个统计维度的所有个数
productgrouped2_count_all = {}
for key,value in productgroup_map.items():
    for v in value:
        productgrouped2_count_all[key] = productgrouped2_count_all.get(key,0) + productgroup_all_china_map.get(v,0)
productgrouped2_count_all['海外合计'] = productgroup_all_oversea_map
print(productgrouped2_count_all)

#匹配出统计周期内的新增个数
productgrouped2_count_part = {}
for key,value in productgroup_map.items():
    for v in value:
        productgrouped2_count_part[key] = productgrouped2_count_part.get(key,0) + productgroup_part_china_map.get(v,0)
productgrouped2_count_part['海外合计'] = productgroup_part_oversea_map
print(productgrouped2_count_part)

{'油烟机': 12867, '灶具': 6762, '蒸烤微合计': 6497, '灶集成': 2366, '烹饪合计': 15625, '水槽洗碗机': 4444, '嵌入式洗碗机': 3930, '洗碗机合计': 8374, '家用净水机': 2769, '热水器': 4643, '净热合计': 7412, '消毒柜': 2623, '国内产品线合计': 46901, '海外合计': 9215}
{'油烟机': 3628, '灶具': 1094, '蒸烤微合计': 1240, '灶集成': 1034, '烹饪合计': 3368, '水槽洗碗机': 784, '嵌入式洗碗机': 1357, '洗碗机合计': 2141, '家用净水机': 1056, '热水器': 672, '净热合计': 1728, '消毒柜': 416, '国内产品线合计': 11281, '海外合计': 1755}

### 构建基准数据表

In [16]:

#构建目标数据的DataFrame首列
df_out = pd.DataFrame()
df_out['产品线'] = ['油烟机产品线', '烹饪厨电产品线', '烹饪厨电产品线', '烹饪厨电产品线', '烹饪厨电产品线', '洗碗机产品线', '洗碗机产品线', '洗碗机产品线', '净热产品线', '净热产品线', '净热产品线', '冰储产品线', '国内产品线合计', '海外合计']
df_out['产品集合']=['油烟机', '灶具', '蒸烤微合计', '灶集成', '烹饪合计', '水槽洗碗机', '嵌入式洗碗机', '洗碗机合计', '家用净水机', '热水器', '净热合计', '消毒柜', '国内产品线合计', '海外合计']
df_out

        产品线     产品集合
0    油烟机产品线      油烟机
1   烹饪厨电产品线       灶具
2   烹饪厨电产品线    蒸烤微合计
3   烹饪厨电产品线      灶集成
4   烹饪厨电产品线     烹饪合计
5    洗碗机产品线    水槽洗碗机
6    洗碗机产品线   嵌入式洗碗机
7    洗碗机产品线    洗碗机合计
8     净热产品线    家用净水机
9     净热产品线      热水器
10    净热产品线     净热合计
11    冰储产品线      消毒柜
12  国内产品线合计  国内产品线合计
13     海外合计     海外合计

In [17]:
df_out[f'{year_name}基准零部件数'] = df_out['产品集合'].map(productgroup_starting_map)
df_out[f'{year_name+month_name}零部件数'] = df_out['产品集合'].map(productgrouped2_count_all)
df_out[f'{year_name}1-{month_name}新建数量'] = df_out['产品集合'].map(productgrouped2_count_part)
df_out['净增加数量'] = df_out[f'{year_name+month_name}零部件数'] - df_out[f'{year_name}基准零部件数']
df_out[f'{year_name}冻结数量'] = df_out[f'{year_name}1-{month_name}新建数量'] - df_out['净增加数量']
df_out['物料精简率'] = (-df_out['净增加数量'] / df_out[f'{year_name}基准零部件数'] * 100).round(2).apply(lambda x: f"{x:.2f}%")
df_out[f'{income_year_name}'] = df_out['产品集合'].map(productgroup_sales_map)
df_out[f'{year_name+month_name}发货收入'] =  df_out['产品集合'].map(productgroup2_income_map)
df_out['基准单物料产值'] = (df_out[f'{income_year_name}'] / df_out[f'{year_name}基准零部件数']).round(2)
df_out[f'{year_name+month_name}单物料产值'] = (df_out[f'{year_name+month_name}发货收入'] / df_out[f'{year_name+month_name}零部件数']).round(2)
df_out['目标'] = df_out['产品集合'].map(target_map)
df_out['发货收入增加率'] =  ((df_out[f'{year_name+month_name}发货收入'] - df_out[f'{income_year_name}']) / df_out[f'{income_year_name}'] * 100).round(2).apply(lambda x: f"{x:.2f}%")
df_out['产值变化率'] = ((df_out[f'{year_name+month_name}单物料产值'] - df_out['基准单物料产值']) / df_out['基准单物料产值'] * 100).round(2).apply(lambda x: f"{x:.2f}%")
df_out['仍需冻结物料数'] = '/'
df_out['同目标差异'] = '/'
df_out = df_out.fillna('/')
for index,row in df_out.iterrows():
    if row['目标'] == '/':
        df_out.loc[index,'仍需冻结物料数'] = '/'
        df_out.loc[index,'同目标差异'] = '/'
    else:
        df_out.loc[index,'仍需冻结物料数'] = df_out.loc[index,f'{year_name+month_name}零部件数'] - df_out.loc[index,f'{year_name+month_name}发货收入'] / df_out.loc[index,'目标']
        df_out.loc[index,'同目标差异'] = df_out.loc[index,f'{year_name+month_name}单物料产值'] - float(df_out.loc[index,'目标'])
        if df_out.loc[index,'仍需冻结物料数'] < 0:
            df_out.loc[index,'仍需冻结物料数'] = '已达标'
        else:
            df_out.loc[index,'仍需冻结物料数'] = np.ceil(df_out.loc[index, '仍需冻结物料数']).astype(int)
df_out['备注'] = df_out['产品集合'].map(beizhu)

df_out

,产品线,产品集合,2025年基准零部件数,2025年12月零部件数,2025年1-12月新建数量,净增加数量,2025年冻结数量,物料精简率,2024年发货收入,2025年12月发货收入,基准单物料产值,2025年12月单物料产值,目标,发货收入增加率,产值变化率,仍需冻结物料数,同目标差异,备注
0,油烟机产品线,油烟机,11823,12867,3628,1044,2584,-8.83%,760275.0,701477.8928,64.3,54.52,58.5,-7.73%,-15.21%,876,-3.98,不含ODM、空调/IMES
1,烹饪厨电产品线,灶具,6485,6762,1094,277,817,-4.27%,364114.0,356352.307,56.15,52.7,49.52,-2.13%,-6.14%,已达标,3.18,不含火炬、智能灶
2,烹饪厨电产品线,蒸烤微合计,6655,6497,1240,-158,1398,2.37%,117582.0,106930.0589,17.67,16.46,16.29,-9.06%,-6.85%,已达标,0.17,含烹饪机
3,烹饪厨电产品线,灶集成,2060,2366,1034,306,728,-14.85%,51586.0,66489.355,25.04,28.1,24.89,28.89%,12.22%,已达标,3.21,不含灶消
4,烹饪厨电产品线,烹饪合计,15200,15625,3368,425,2943,-2.80%,533281.0,529771.7209,35.08,33.91,31.49,-0.66%,-3.34%,已达标,2.42,不含灶消
5,洗碗机产品线,水槽洗碗机,4088,4444,784,356,428,-8.71%,70840.0,78748.0245,17.33,17.72,/,11.16%,2.25%,/,/,/
6,洗碗机产品线,嵌入式洗碗机,2936,3930,1357,994,363,-33.86%,129987.0,136885.049,44.27,34.83,/,5.31%,-21.32%,/,/,/
7,洗碗机产品线,洗碗机合计,7024,8374,2141,1350,791,-19.22%,200827.0,215633.0735,28.59,25.75,25.73,7.37%,-9.93%,已达标,0.02,/
8,净热产品线,家用净水机,2083,2769,1056,686,370,-32.93%,21298.0,21576.175,10.22,7.79,9.2,1.31%,-23.78%,424,-1.41,/
9,净热产品线,热水器,4352,4643,672,291,381,-6.69%,50544.0,46095.6464,11.61,9.93,10.45,-8.80%,-14.47%,232,-0.52,含两用炉
10,净热产品线,净热合计,6435,7412,1728,977,751,-15.18%,71842.0,67671.8214,11.16,9.13,10.04,-5.80%,-18.19%,672,-0.91,/
11,冰储产品线,消毒柜,2589,2623,416,34,382,-1.31%,51444.0,38127.714,19.87,14.54,14.5,-25.89%,-26.82%,已达标,0.04,/
12,国内产品线合计,国内产品线合计,43071,46901,11281,3830,7451,-8.89%,1617669.0,1552682.2226,37.56,33.11,33.8,-4.02%,-11.85%,964,-0.69,/
13,海外合计,海外合计,7547,9215,1755,1668,87,-22.10%,/,/,/,/,/,nan%,nan%,/,/,/

### 产品线单物料产值（表格）

In [18]:
df_out1 = df_out[df_out['产品集合'].isin(['油烟机','烹饪合计','洗碗机合计','净热合计','消毒柜'])]
df_out1['同目标差异'] = df_out1[f'{year_name+month_name}单物料产值'] - df_out1['目标']
df_out1 = df_out1[['产品线','产品集合','基准单物料产值',f'{year_name+month_name}单物料产值','目标','同目标差异','产值变化率']]
display(df_out1)

C:\Users\zhangbon\AppData\Local\Temp\ipykernel_21612\151329981.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_out1['同目标差异'] = df_out1[f'{year_name+month_name}单物料产值'] - df_out1['目标']

        产品线   产品集合 基准单物料产值 2025年12月单物料产值     目标 同目标差异    产值变化率
0    油烟机产品线    油烟机    64.3         54.52   58.5 -3.98  -15.21%
4   烹饪厨电产品线   烹饪合计   35.08         33.91  31.49  2.42   -3.34%
7    洗碗机产品线  洗碗机合计   28.59         25.75  25.73  0.02   -9.93%
10    净热产品线   净热合计   11.16          9.13  10.04 -0.91  -18.19%
11    冰储产品线    消毒柜   19.87         14.54   14.5  0.04  -26.82%

### 产品组单物料产值

In [19]:
df_out2 = df_out[['产品线',	'产品集合','基准单物料产值','目标',	f'{year_name}{month_name}单物料产值','同目标差异','产值变化率','物料精简率','备注',	'仍需冻结物料数']]
df_out2 = df_out2.rename(columns={'仍需冻结物料数': '是否达标'})
df_out2

,产品线,产品集合,基准单物料产值,目标,2025年12月单物料产值,同目标差异,产值变化率,物料精简率,备注,是否达标
0,油烟机产品线,油烟机,64.3,58.5,54.52,-3.98,-15.21%,-8.83%,不含ODM、空调/IMES,876
1,烹饪厨电产品线,灶具,56.15,49.52,52.7,3.18,-6.14%,-4.27%,不含火炬、智能灶,已达标
2,烹饪厨电产品线,蒸烤微合计,17.67,16.29,16.46,0.17,-6.85%,2.37%,含烹饪机,已达标
3,烹饪厨电产品线,灶集成,25.04,24.89,28.1,3.21,12.22%,-14.85%,不含灶消,已达标
4,烹饪厨电产品线,烹饪合计,35.08,31.49,33.91,2.42,-3.34%,-2.80%,不含灶消,已达标
5,洗碗机产品线,水槽洗碗机,17.33,/,17.72,/,2.25%,-8.71%,/,/
6,洗碗机产品线,嵌入式洗碗机,44.27,/,34.83,/,-21.32%,-33.86%,/,/
7,洗碗机产品线,洗碗机合计,28.59,25.73,25.75,0.02,-9.93%,-19.22%,/,已达标
8,净热产品线,家用净水机,10.22,9.2,7.79,-1.41,-23.78%,-32.93%,/,424
9,净热产品线,热水器,11.61,10.45,9.93,-0.52,-14.47%,-6.69%,含两用炉,232
10,净热产品线,净热合计,11.16,10.04,9.13,-0.91,-18.19%,-15.18%,/,672
11,冰储产品线,消毒柜,19.87,14.5,14.54,0.04,-26.82%,-1.31%,/,已达标
12,国内产品线合计,国内产品线合计,37.56,33.8,33.11,-0.69,-11.85%,-8.89%,/,964
13,海外合计,海外合计,/,/,/,/,nan%,-22.10%,/,/

## 物料精简率

### 产品线精简率

In [20]:
df_out3 = df_out.loc[df_out['产品集合'].isin(['油烟机','烹饪合计','洗碗机合计','净热合计','消毒柜','国内产品线合计','海外合计']),['产品线','产品集合','物料精简率']]
df_out3

        产品线     产品集合    物料精简率
0    油烟机产品线      油烟机   -8.83%
4   烹饪厨电产品线     烹饪合计   -2.80%
7    洗碗机产品线    洗碗机合计  -19.22%
10    净热产品线     净热合计  -15.18%
11    冰储产品线      消毒柜   -1.31%
12  国内产品线合计  国内产品线合计   -8.89%
13     海外合计     海外合计  -22.10%

### 产品组精简率

In [21]:
df_out4 = df_out[['产品线', '产品集合', f'{year_name}基准零部件数' ,f'{year_name+month_name}零部件数',f'{year_name}1-{month_name}新建数量',f'{year_name}冻结数量','净增加数量','物料精简率','备注']]
df_out4

,产品线,产品集合,2025年基准零部件数,2025年12月零部件数,2025年1-12月新建数量,2025年冻结数量,净增加数量,物料精简率,备注
0,油烟机产品线,油烟机,11823,12867,3628,2584,1044,-8.83%,不含ODM、空调/IMES
1,烹饪厨电产品线,灶具,6485,6762,1094,817,277,-4.27%,不含火炬、智能灶
2,烹饪厨电产品线,蒸烤微合计,6655,6497,1240,1398,-158,2.37%,含烹饪机
3,烹饪厨电产品线,灶集成,2060,2366,1034,728,306,-14.85%,不含灶消
4,烹饪厨电产品线,烹饪合计,15200,15625,3368,2943,425,-2.80%,不含灶消
5,洗碗机产品线,水槽洗碗机,4088,4444,784,428,356,-8.71%,/
6,洗碗机产品线,嵌入式洗碗机,2936,3930,1357,363,994,-33.86%,/
7,洗碗机产品线,洗碗机合计,7024,8374,2141,791,1350,-19.22%,/
8,净热产品线,家用净水机,2083,2769,1056,370,686,-32.93%,/
9,净热产品线,热水器,4352,4643,672,381,291,-6.69%,含两用炉
10,净热产品线,净热合计,6435,7412,1728,751,977,-15.18%,/
11,冰储产品线,消毒柜,2589,2623,416,382,34,-1.31%,/
12,国内产品线合计,国内产品线合计,43071,46901,11281,7451,3830,-8.89%,/
13,海外合计,海外合计,7547,9215,1755,87,1668,-22.10%,/

# 结果导出

In [22]:
#将df_out,df_out1,df_out2放到3个sheet并导出
with pd.ExcelWriter(rf'D:\000物料报表\{month}\单物料产值\物料精简报表.xlsx') as writer:
    df_out.to_excel(writer, sheet_name='sheet1', index=False)
    df_out1.to_excel(writer, sheet_name='产品线单物料产值', index=False)
    df_out2.to_excel(writer, sheet_name='产品组单物料产值', index=False)
    df_out3.to_excel(writer, sheet_name='产品线精简率', index=False)
    df_out4.to_excel(writer, sheet_name='产品组精简率', index=False)