In [133]:
import pandas as pd
import openpyxl
from IPython.display import display
import xlsxwriter
import numpy as np

In [134]:
#指定月份
month = '202506'
#指定时间范围
start_date = pd.Timestamp('2025-01-01')
end_date = pd.Timestamp('2025-06-30')
df = pd.read_excel(fr"D:\000物料报表\{month}\单物料产值\物料精简原始数据6月.XLSX")
df

,物料编码,创建日期,是否冻结,图号,产品组,跨工厂物料状态,是否虚拟物料,国内/海外,物料描述
0,1101000100400,2018-07-10,X,1-FAA-A004,Z1,NaN,NaN,国内,垫脚(CXW-128-Q2)
1,1101000100410,2018-07-10,NaN,1-FAA-A106,Z1,NaN,NaN,国内,线夹(CXW-128-Q2)
2,1101000100430,2018-07-10,X,1-FAA-A200,Z1,NaN,NaN,国内,上导风板组件(CXW-128-Q2)
3,1101000100440,2018-07-10,X,1-FAA-A201,Z1,NaN,NaN,国内,连接圈(CXW-128-Q2)
4,1101000100450,2018-07-10,X,1-FAA-A211,Z1,NaN,NaN,国内,上导风板(CXW-128-Q2)
...,...,...,...,...,...,...,...,...,...
121202,112500040005A,2024-07-05,NaN,SAEG-N0011,F1,NaN,NaN,国内,附件包装盒_542*382*44_FJ-YKZP2
121203,112500040005B,2024-07-16,NaN,SAEG-N0011,F1,NaN,NaN,国内,附件包装盒_542*382*44_FJ-YKZP2
121204,112500040010A,2024-06-27,NaN,SAEF-A0010,F1,NaN,NaN,国内,蒸烤盘_银色_FJ-YKZP1
121205,112500040018A,2024-06-25,NaN,SAEH-A0010,F1,NaN,NaN,国内,蒸烤盘_银色_FJ-YKZP3
121206,112500060000A,2025-01-02,NaN,FATB-A2000,F1,NaN,NaN,国内,铝箔出风管组件_φ160_4m_BBF-B-16-AA1

In [135]:
df = df.astype(str)

In [136]:
list_drop = []
df['删除原因'] = '空'
for i in range(len(df)):
    # if df.loc[i,'国内/海外'] == 10:
    #     list_drop.append(i)
    #     df.loc[i,'删除原因'] = '海外'
    if 'ZD70' in df.loc[i,'物料描述']:
        list_drop.append(i)
        df.loc[i,'删除原因'] = 'ODM'
    if df.loc[i,'图号'][:4] == 'LAFS':
        list_drop.append(i)
        df.loc[i,'删除原因'] = '火炬'
    if df.loc[i,'图号'][:4] == 'LAFT':
        list_drop.append(i)
        df.loc[i,'删除原因'] = '火炬'
    if df.loc[i,'物料编码'][:8] == '11010022':
        list_drop.append(i)
        df.loc[i,'删除原因'] = 'IMES'  
    if df.loc[i,'物料编码'][:8] == '11010027':
        list_drop.append(i)
        df.loc[i,'删除原因'] = '空调油烟机'  
    if df.loc[i,'图号'][:4] == 'PACA':
        list_drop.append(i)
        df.loc[i,'删除原因'] = '净存机'
    if df.loc[i,'产品组'] == 'ZN':
        list_drop.append(i)
        df.loc[i,'删除原因'] = '灶消'

In [137]:
df

,物料编码,创建日期,是否冻结,图号,产品组,跨工厂物料状态,是否虚拟物料,国内/海外,物料描述,删除原因
0,1101000100400,2018-07-10,X,1-FAA-A004,Z1,nan,nan,国内,垫脚(CXW-128-Q2),空
1,1101000100410,2018-07-10,nan,1-FAA-A106,Z1,nan,nan,国内,线夹(CXW-128-Q2),空
2,1101000100430,2018-07-10,X,1-FAA-A200,Z1,nan,nan,国内,上导风板组件(CXW-128-Q2),空
3,1101000100440,2018-07-10,X,1-FAA-A201,Z1,nan,nan,国内,连接圈(CXW-128-Q2),空
4,1101000100450,2018-07-10,X,1-FAA-A211,Z1,nan,nan,国内,上导风板(CXW-128-Q2),空
...,...,...,...,...,...,...,...,...,...,...
121202,112500040005A,2024-07-05,nan,SAEG-N0011,F1,nan,nan,国内,附件包装盒_542*382*44_FJ-YKZP2,空
121203,112500040005B,2024-07-16,nan,SAEG-N0011,F1,nan,nan,国内,附件包装盒_542*382*44_FJ-YKZP2,空
121204,112500040010A,2024-06-27,nan,SAEF-A0010,F1,nan,nan,国内,蒸烤盘_银色_FJ-YKZP1,空
121205,112500040018A,2024-06-25,nan,SAEH-A0010,F1,nan,nan,国内,蒸烤盘_银色_FJ-YKZP3,空
121206,112500060000A,2025-01-02,nan,FATB-A2000,F1,nan,nan,国内,铝箔出风管组件_φ160_4m_BBF-B-16-AA1,空

In [138]:
len(list_drop)

2002

In [139]:
#依据产品组的产品组描述的对照关系，生成一列产品组描述
# 输入：字典, 产品组描述的对照关系，产品组描述的列名
product_dict = {
    'Z1': '油烟机',
    'ZZ': '不考核产品',
    'Z2': '灶具',
    'Z3': '消毒柜',
    'Z7': '热水器',
    'ZT': '热水器',
    'Z6': '烤箱',
    'Z4': '微波炉',
    'Z5': '蒸箱',  
    'Z8': '水槽洗碗机',
    'ZK': '蒸微',
    'ZL': '蒸烤烹饪机',
    'ZM': '灶集成',
    'ZP': '灶集成',
    'ZN': '灶集成',
    'ZQ': '蒸烤微烹饪机',
    'Y1': '不考核产品',
    'Y4': '灶烤烹饪机',
    'Z9': '不考核产品',
    'ZA': '不考核产品',
    'ZD': '家用净水机',
    'ZR': '不考核产品',
    'ZU': '不考核产品',
    'ZE': '不考核产品',
    'ZH': '不考核产品',
    'ZJ': '不考核产品',
    'ZS': '嵌入式洗碗机',
    'ZV': '不考核产品',
    'ZX': '不考核产品',
    'Y2': '不考核产品',
    'Y3': '不考核产品',
    'F1': '不考核产品'
}
df['产品组描述'] = df['产品组'].map(product_dict)

In [140]:
#依据产品组的国内海外的对照关系，生成一列国内/海外描述
# 输入：字典, 产品组描述的对照关系，产品组描述的列名
product_group_description_dict = {'20': '国内', '10': '海外','国内': '国内', '海外': '海外',20: '国内', 10: '海外','20.0': '国内', '10.0': '海外'}
df['国内/海外描述'] = df['国内/海外'].map(product_group_description_dict)
df = df.fillna('空')
df

,物料编码,创建日期,是否冻结,图号,产品组,跨工厂物料状态,是否虚拟物料,国内/海外,物料描述,删除原因,产品组描述,国内/海外描述
0,1101000100400,2018-07-10,X,1-FAA-A004,Z1,nan,nan,国内,垫脚(CXW-128-Q2),空,油烟机,国内
1,1101000100410,2018-07-10,nan,1-FAA-A106,Z1,nan,nan,国内,线夹(CXW-128-Q2),空,油烟机,国内
2,1101000100430,2018-07-10,X,1-FAA-A200,Z1,nan,nan,国内,上导风板组件(CXW-128-Q2),空,油烟机,国内
3,1101000100440,2018-07-10,X,1-FAA-A201,Z1,nan,nan,国内,连接圈(CXW-128-Q2),空,油烟机,国内
4,1101000100450,2018-07-10,X,1-FAA-A211,Z1,nan,nan,国内,上导风板(CXW-128-Q2),空,油烟机,国内
...,...,...,...,...,...,...,...,...,...,...,...,...
121202,112500040005A,2024-07-05,nan,SAEG-N0011,F1,nan,nan,国内,附件包装盒_542*382*44_FJ-YKZP2,空,不考核产品,国内
121203,112500040005B,2024-07-16,nan,SAEG-N0011,F1,nan,nan,国内,附件包装盒_542*382*44_FJ-YKZP2,空,不考核产品,国内
121204,112500040010A,2024-06-27,nan,SAEF-A0010,F1,nan,nan,国内,蒸烤盘_银色_FJ-YKZP1,空,不考核产品,国内
121205,112500040018A,2024-06-25,nan,SAEH-A0010,F1,nan,nan,国内,蒸烤盘_银色_FJ-YKZP3,空,不考核产品,国内
121206,112500060000A,2025-01-02,nan,FATB-A2000,F1,nan,nan,国内,铝箔出风管组件_φ160_4m_BBF-B-16-AA1,空,不考核产品,国内

In [141]:
df.to_excel(fr"D:\000物料报表\{month}\单物料产值\物料精简原始数据处理稿.xlsx",index=False)

In [142]:
df = df.replace('nan','空')
df

,物料编码,创建日期,是否冻结,图号,产品组,跨工厂物料状态,是否虚拟物料,国内/海外,物料描述,删除原因,产品组描述,国内/海外描述
0,1101000100400,2018-07-10,X,1-FAA-A004,Z1,空,空,国内,垫脚(CXW-128-Q2),空,油烟机,国内
1,1101000100410,2018-07-10,空,1-FAA-A106,Z1,空,空,国内,线夹(CXW-128-Q2),空,油烟机,国内
2,1101000100430,2018-07-10,X,1-FAA-A200,Z1,空,空,国内,上导风板组件(CXW-128-Q2),空,油烟机,国内
3,1101000100440,2018-07-10,X,1-FAA-A201,Z1,空,空,国内,连接圈(CXW-128-Q2),空,油烟机,国内
4,1101000100450,2018-07-10,X,1-FAA-A211,Z1,空,空,国内,上导风板(CXW-128-Q2),空,油烟机,国内
...,...,...,...,...,...,...,...,...,...,...,...,...
121202,112500040005A,2024-07-05,空,SAEG-N0011,F1,空,空,国内,附件包装盒_542*382*44_FJ-YKZP2,空,不考核产品,国内
121203,112500040005B,2024-07-16,空,SAEG-N0011,F1,空,空,国内,附件包装盒_542*382*44_FJ-YKZP2,空,不考核产品,国内
121204,112500040010A,2024-06-27,空,SAEF-A0010,F1,空,空,国内,蒸烤盘_银色_FJ-YKZP1,空,不考核产品,国内
121205,112500040018A,2024-06-25,空,SAEH-A0010,F1,空,空,国内,蒸烤盘_银色_FJ-YKZP3,空,不考核产品,国内
121206,112500060000A,2025-01-02,空,FATB-A2000,F1,空,空,国内,铝箔出风管组件_φ160_4m_BBF-B-16-AA1,空,不考核产品,国内

In [143]:
#先筛出删除原因为空的df,且非虚拟物料
df_not_del = df[(df["删除原因"] == "空")&(df["是否虚拟物料"] == "空")]
df_not_del

,物料编码,创建日期,是否冻结,图号,产品组,跨工厂物料状态,是否虚拟物料,国内/海外,物料描述,删除原因,产品组描述,国内/海外描述
0,1101000100400,2018-07-10,X,1-FAA-A004,Z1,空,空,国内,垫脚(CXW-128-Q2),空,油烟机,国内
1,1101000100410,2018-07-10,空,1-FAA-A106,Z1,空,空,国内,线夹(CXW-128-Q2),空,油烟机,国内
2,1101000100430,2018-07-10,X,1-FAA-A200,Z1,空,空,国内,上导风板组件(CXW-128-Q2),空,油烟机,国内
3,1101000100440,2018-07-10,X,1-FAA-A201,Z1,空,空,国内,连接圈(CXW-128-Q2),空,油烟机,国内
4,1101000100450,2018-07-10,X,1-FAA-A211,Z1,空,空,国内,上导风板(CXW-128-Q2),空,油烟机,国内
...,...,...,...,...,...,...,...,...,...,...,...,...
121202,112500040005A,2024-07-05,空,SAEG-N0011,F1,空,空,国内,附件包装盒_542*382*44_FJ-YKZP2,空,不考核产品,国内
121203,112500040005B,2024-07-16,空,SAEG-N0011,F1,空,空,国内,附件包装盒_542*382*44_FJ-YKZP2,空,不考核产品,国内
121204,112500040010A,2024-06-27,空,SAEF-A0010,F1,空,空,国内,蒸烤盘_银色_FJ-YKZP1,空,不考核产品,国内
121205,112500040018A,2024-06-25,空,SAEH-A0010,F1,空,空,国内,蒸烤盘_银色_FJ-YKZP3,空,不考核产品,国内
121206,112500060000A,2025-01-02,空,FATB-A2000,F1,空,空,国内,铝箔出风管组件_φ160_4m_BBF-B-16-AA1,空,不考核产品,国内

先对未冻结的做处理

In [144]:
#先对未冻结的做处理
df_not_froze = df_not_del[df_not_del["是否冻结"] == "空"]
df_not_froze["创建日期"] = pd.to_datetime(df_not_froze["创建日期"])
df_not_froze

C:\Users\zhangbon\AppData\Local\Temp\ipykernel_16100\878873356.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_not_froze["创建日期"] = pd.to_datetime(df_not_froze["创建日期"])

,物料编码,创建日期,是否冻结,图号,产品组,跨工厂物料状态,是否虚拟物料,国内/海外,物料描述,删除原因,产品组描述,国内/海外描述
1,1101000100410,2018-07-10,空,1-FAA-A106,Z1,空,空,国内,线夹(CXW-128-Q2),空,油烟机,国内
5,1101000100470,2018-07-10,空,1-FAA-A221,Z1,空,空,国内,网圈(CXW-128-Q2),空,油烟机,国内
6,1101000100480,2018-07-10,空,1-FAA-A222,Z1,空,空,国内,网罩内圈(CXW-128-Q2),空,油烟机,国内
8,1101000100510,2018-07-10,空,1-FAA-A302,Z1,空,空,国内,左灯罩(CXW-128-Q2),空,油烟机,国内
9,1101000100520,2018-07-10,空,1-FAA-A303,Z1,空,空,国内,右灯罩(CXW-128-Q2),空,油烟机,国内
...,...,...,...,...,...,...,...,...,...,...,...,...
121202,112500040005A,2024-07-05,空,SAEG-N0011,F1,空,空,国内,附件包装盒_542*382*44_FJ-YKZP2,空,不考核产品,国内
121203,112500040005B,2024-07-16,空,SAEG-N0011,F1,空,空,国内,附件包装盒_542*382*44_FJ-YKZP2,空,不考核产品,国内
121204,112500040010A,2024-06-27,空,SAEF-A0010,F1,空,空,国内,蒸烤盘_银色_FJ-YKZP1,空,不考核产品,国内
121205,112500040018A,2024-06-25,空,SAEH-A0010,F1,空,空,国内,蒸烤盘_银色_FJ-YKZP3,空,不考核产品,国内
121206,112500060000A,2025-01-02,空,FATB-A2000,F1,空,空,国内,铝箔出风管组件_φ160_4m_BBF-B-16-AA1,空,不考核产品,国内

In [145]:
#对未冻结的国内的物料进行处理
df_not_froze_china = df_not_froze[df_not_froze["国内/海外"] == "国内"]
#对于国内的所有进行处理
df_not_froze_china_all = df_not_froze_china[df_not_froze_china['创建日期'] <= end_date ].groupby(['产品组描述']).size().reset_index(name='数量')
df_not_froze_china_part = df_not_froze_china[(df_not_froze_china['创建日期'] >= start_date ) & (df_not_froze_china['创建日期'] <= end_date )].groupby(['产品组描述']).size().reset_index(name='数量')
with pd.ExcelWriter(fr"D:\000物料报表\{month}\单物料产值\非冻结计数—国内.xlsx") as writer:
    df_not_froze_china_all.to_excel(writer, sheet_name='国内-all', index=False)
    df_not_froze_china_part.to_excel(writer, sheet_name='国内-part', index=False)
df_not_froze_china_all

     产品组描述     数量
0    不考核产品   7960
1    家用净水机   2521
2   嵌入式洗碗机   3200
3      微波炉    629
4    水槽洗碗机   4104
5      油烟机  13164
6      消毒柜   2761
7       灶具   6672
8      灶集成   2198
9       烤箱   1393
10     热水器   4280
11      蒸微    484
12  蒸烤微烹饪机    558
13   蒸烤烹饪机   2595
14      蒸箱   1704

In [146]:
#对未冻结的国外的物料进行处理
df_not_froze_oversea = df_not_froze[df_not_froze["国内/海外"] == "海外"]
df_not_froze_oversea_all = df_not_froze_oversea[df_not_froze_oversea['创建日期'] <= end_date ].groupby(['产品组描述']).size().reset_index(name='数量')
df_not_froze_oversea_part = df_not_froze_oversea[(df_not_froze_oversea['创建日期'] >= start_date ) & (df_not_froze_oversea['创建日期'] <= end_date )].groupby(['产品组描述']).size().reset_index(name='数量')
with pd.ExcelWriter(fr"D:\000物料报表\{month}\单物料产值\非冻结计数—海外.xlsx") as writer:
    df_not_froze_oversea_all.to_excel(writer, sheet_name='海外-all', index=False)
    df_not_froze_oversea_part.to_excel(writer, sheet_name='海外-part', index=False)
print(f'海外物料总数量为：{sum(df_not_froze_oversea_all["数量"])}')
print(f'海外物料限定范围内数量为：{sum(df_not_froze_oversea_part["数量"])}')
print(f'海外物料总数量(去除不考核产品)为：{sum(df_not_froze_oversea_all[~(df_not_froze_oversea_all["产品组描述"]=="不考核产品")]["数量"])}')
print(f'海外物料限定范围内数量(去除不考核产品)为：{sum(df_not_froze_oversea_part[~(df_not_froze_oversea_part["产品组描述"]=="不考核产品")]["数量"])}')

海外物料总数量为：8474
海外物料限定范围内数量为：941
海外物料总数量(去除不考核产品)为：8407
海外物料限定范围内数量(去除不考核产品)为：925

对剔除掉冻结或采购冻结的值

In [147]:
#筛选出跨工厂物料状态为空且是否冻结为空
df_not_caigou_froze = df_not_del[(df_not_del['跨工厂物料状态'] == '空') & (df_not_del['是否冻结'] == "空")]
df_not_caigou_froze["创建日期"] = pd.to_datetime(df_not_caigou_froze["创建日期"])
df_not_caigou_froze

C:\Users\zhangbon\AppData\Local\Temp\ipykernel_16100\1626582603.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_not_caigou_froze["创建日期"] = pd.to_datetime(df_not_caigou_froze["创建日期"])

,物料编码,创建日期,是否冻结,图号,产品组,跨工厂物料状态,是否虚拟物料,国内/海外,物料描述,删除原因,产品组描述,国内/海外描述
1,1101000100410,2018-07-10,空,1-FAA-A106,Z1,空,空,国内,线夹(CXW-128-Q2),空,油烟机,国内
5,1101000100470,2018-07-10,空,1-FAA-A221,Z1,空,空,国内,网圈(CXW-128-Q2),空,油烟机,国内
6,1101000100480,2018-07-10,空,1-FAA-A222,Z1,空,空,国内,网罩内圈(CXW-128-Q2),空,油烟机,国内
8,1101000100510,2018-07-10,空,1-FAA-A302,Z1,空,空,国内,左灯罩(CXW-128-Q2),空,油烟机,国内
9,1101000100520,2018-07-10,空,1-FAA-A303,Z1,空,空,国内,右灯罩(CXW-128-Q2),空,油烟机,国内
...,...,...,...,...,...,...,...,...,...,...,...,...
121202,112500040005A,2024-07-05,空,SAEG-N0011,F1,空,空,国内,附件包装盒_542*382*44_FJ-YKZP2,空,不考核产品,国内
121203,112500040005B,2024-07-16,空,SAEG-N0011,F1,空,空,国内,附件包装盒_542*382*44_FJ-YKZP2,空,不考核产品,国内
121204,112500040010A,2024-06-27,空,SAEF-A0010,F1,空,空,国内,蒸烤盘_银色_FJ-YKZP1,空,不考核产品,国内
121205,112500040018A,2024-06-25,空,SAEH-A0010,F1,空,空,国内,蒸烤盘_银色_FJ-YKZP3,空,不考核产品,国内
121206,112500060000A,2025-01-02,空,FATB-A2000,F1,空,空,国内,铝箔出风管组件_φ160_4m_BBF-B-16-AA1,空,不考核产品,国内

In [148]:
#对非采购冻结和冻结的国内物料进行处理
df_not_caigou_froze_china = df_not_caigou_froze[df_not_caigou_froze["国内/海外"] == "国内"]
df_not_caigou_froze_china['创建日期'] = pd.to_datetime(df_not_caigou_froze_china['创建日期'])
#对于国内的进行处理
df_not_caigou_froze_china_all = df_not_caigou_froze_china[df_not_caigou_froze_china['创建日期'] <= end_date ].groupby(['产品组描述']).size().reset_index(name='数量')
df_not_caigou_froze_china_part = df_not_caigou_froze_china[(df_not_caigou_froze_china['创建日期'] >= start_date ) & (df_not_caigou_froze_china['创建日期'] <= end_date )].groupby(['产品组描述']).size().reset_index(name='数量')
with pd.ExcelWriter(fr"D:\000物料报表\{month}\单物料产值\非采购非冻结计数—国内.xlsx") as writer:
    df_not_caigou_froze_china_all.to_excel(writer, sheet_name='国内-all', index=False)
    df_not_caigou_froze_china_part.to_excel(writer, sheet_name='国内-part', index=False)
df_not_caigou_froze_china_all

C:\Users\zhangbon\AppData\Local\Temp\ipykernel_16100\3517800379.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_not_caigou_froze_china['创建日期'] = pd.to_datetime(df_not_caigou_froze_china['创建日期'])

     产品组描述     数量
0    不考核产品   7960
1    家用净水机   2521
2   嵌入式洗碗机   3200
3      微波炉    564
4    水槽洗碗机   4104
5      油烟机  11710
6      消毒柜   2761
7       灶具   6148
8      灶集成   2001
9       烤箱   1205
10     热水器   4221
11      蒸微    423
12  蒸烤微烹饪机    523
13   蒸烤烹饪机   2395
14      蒸箱   1497

In [149]:
#对于海外的进行处理
df_not_caigou_froze_oversea = df_not_caigou_froze[df_not_caigou_froze["国内/海外"] == "海外"]
df_not_caigou_froze_oversea["创建日期"] = pd.to_datetime(df_not_caigou_froze_oversea['创建日期'])
#对于国内的所有进行处理
df_not_caigou_froze_oversea_all = df_not_caigou_froze_oversea[df_not_caigou_froze_oversea['创建日期'] <= end_date ].groupby(['产品组描述']).size().reset_index(name='数量')
#对于海外的进行处理
df_not_caigou_froze_oversea_part = df_not_caigou_froze_oversea[(df_not_caigou_froze_oversea['创建日期'] >= start_date ) & (df_not_caigou_froze_oversea['创建日期'] <= end_date )].groupby(['产品组描述']).size().reset_index(name='数量')
with pd.ExcelWriter(fr"D:\000物料报表\{month}\单物料产值\非采购非冻结计数—海外.xlsx") as writer:
    df_not_caigou_froze_oversea_all.to_excel(writer, sheet_name='海外-all', index=False)
    df_not_caigou_froze_oversea_part.to_excel(writer, sheet_name='海外-part', index=False)
df_not_caigou_froze_oversea_all
print(f'非采购非冻结海外物料总数量为：{sum(df_not_caigou_froze_oversea_all["数量"])}')
print(f'非采购非冻结海外物料限定范围内数量为：{sum(df_not_caigou_froze_oversea_part["数量"])}')
print(f'非采购非冻结海外物料总数量(去除不考核产品)为：{sum(df_not_caigou_froze_oversea_all[~(df_not_caigou_froze_oversea_all["产品组描述"]=="不考核产品")]["数量"])}')
print(f'非采购非冻结海外物料限定范围内数量(去除不考核产品)为：{sum(df_not_caigou_froze_oversea_part[~(df_not_caigou_froze_oversea_part["产品组描述"]=="不考核产品")]["数量"])}')

非采购非冻结海外物料总数量为：8473
非采购非冻结海外物料限定范围内数量为：941
非采购非冻结海外物料总数量(去除不考核产品)为：8406
非采购非冻结海外物料限定范围内数量(去除不考核产品)为：925

C:\Users\zhangbon\AppData\Local\Temp\ipykernel_16100\1267856069.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_not_caigou_froze_oversea["创建日期"] = pd.to_datetime(df_not_caigou_froze_oversea['创建日期'])