In [90]:
import pandas as pd
import os

In [105]:
# 物流的渠道对照关系清洗用
month = 202512
Channel_map = {
'工程': '工程',
'零售':'零售',
'电商不可售':'电商',
'电商':'电商',
'内部处理通用':'电商',
'借出渠道':'非零售工程电商',
'新品':'电商',
'战略电商':'电商',
'转出渠道':'非零售工程电商',
'每誉':'每誉',
'商净':'商净',
'渠道':'非零售工程电商',
'海外':'海外',
'调出渠道':'非零售工程电商',
'非零售工程电商':'非零售工程电商',
'米博新零售':'米博新零售'
}
#用于合并计算
productgroupset_map = {
    '吸油烟机':['吸油烟机'],
    '灶具':['灶具'],
    '烤箱':['烤箱'],
    '蒸箱':['蒸箱'],
    '微波炉':['微波炉'],
    '蒸烤烹饪机':['蒸烤烹饪机'],
    '蒸烤微烹饪机':['蒸烤微烹饪机'],
    '蒸微':['蒸微'],
    '蒸烤微合计':['烤箱','蒸箱','微波炉','蒸烤烹饪机','蒸烤微烹饪机','蒸微'],
    '灶消烹饪机':['灶消烹饪机'],
    '灶蒸烹饪机':['灶蒸烹饪机'],
    '灶蒸烤烹饪机':['灶蒸烤烹饪机'],
    '灶烤烹饪机':['灶烤烹饪机'],
    '灶集成':['灶消烹饪机','灶蒸烹饪机','灶蒸烤烹饪机','灶烤烹饪机'],
    '烹饪产品线合计':['灶具','烤箱','蒸箱','微波炉','蒸烤烹饪机','蒸烤微烹饪机','蒸微','灶消烹饪机','灶蒸烹饪机','灶蒸烤烹饪机','灶烤烹饪机'],
    '消毒柜':['消毒柜'],
    '热水器':['热水器'],
    '两用炉':['两用炉'],
    '热水器两用炉合计':['热水器','两用炉'],
    '家用净水机':['家用净水机'],
    '商用净水机':['商用净水机'],
    '净热产品线合计':['热水器','两用炉','家用净水机','商用净水机'],
    '水槽洗碗机':['水槽洗碗机'],
    '嵌入式洗碗机':['嵌入式洗碗机'],
    '洗碗机产品线合计':['水槽洗碗机','嵌入式洗碗机'],
    '国内合计':['吸油烟机','灶具','烤箱','蒸箱','微波炉','蒸烤烹饪机','蒸烤微烹饪机','蒸微','灶消烹饪机','灶蒸烹饪机','灶蒸烤烹饪机','灶烤烹饪机','消毒柜','热水器','两用炉','家用净水机','商用净水机','水槽洗碗机','嵌入式洗碗机'],
}
# 统计的产品组
productgroup_list = ['吸油烟机','灶具','烤箱','蒸箱','微波炉','蒸烤烹饪机','蒸烤微烹饪机','蒸微','灶消烹饪机','灶蒸烹饪机','灶蒸烤烹饪机','灶烤烹饪机','消毒柜','热水器','两用炉','热水器两用炉合计','家用净水机','商用净水机','净热产品线合计','水槽洗碗机','嵌入式洗碗机','洗碗机产品线合计','国内合计']

In [106]:
#将这些excel的表格数据进行上下拼接，只要字段：商品编码、商品名称、渠道、实际出库数量
folder_path = fr"D:\000物料报表\202511\单型号贡献-低效-长尾\物流发货"  # 请替换为实际的文件夹路径
excel_files = []
for root, dirs, files in os.walk(folder_path):
    for file in files:
        sheet_names = file[5:].replace(file[-5:],'')
        if (file.endswith('.xlsx') or file.endswith('.xls')) and not file.startswith('~$'):
            file_path = os.path.join(root, file)
            excel_files.append((file, sheet_names, file_path))
print(excel_files)

[('2025年10月明细.xlsx', '10月明细', 'D:\\000物料报表\\202511\\单型号贡献-低效-长尾\\物流发货\\2025年10月明细.xlsx'), ('2025年11月明细.xlsx', '11月明细', 'D:\\000物料报表\\202511\\单型号贡献-低效-长尾\\物流发货\\2025年11月明细.xlsx'), ('2025年1月明细.xlsx', '1月明细', 'D:\\000物料报表\\202511\\单型号贡献-低效-长尾\\物流发货\\2025年1月明细.xlsx'), ('2025年2月明细.xlsx', '2月明细', 'D:\\000物料报表\\202511\\单型号贡献-低效-长尾\\物流发货\\2025年2月明细.xlsx'), ('2025年3月明细.xlsx', '3月明细', 'D:\\000物料报表\\202511\\单型号贡献-低效-长尾\\物流发货\\2025年3月明细.xlsx'), ('2025年4月明细.xlsx', '4月明细', 'D:\\000物料报表\\202511\\单型号贡献-低效-长尾\\物流发货\\2025年4月明细.xlsx'), ('2025年5月明细.xlsx', '5月明细', 'D:\\000物料报表\\202511\\单型号贡献-低效-长尾\\物流发货\\2025年5月明细.xlsx'), ('2025年6月明细.xlsx', '6月明细', 'D:\\000物料报表\\202511\\单型号贡献-低效-长尾\\物流发货\\2025年6月明细.xlsx'), ('2025年7月明细.xlsx', '7月明细', 'D:\\000物料报表\\202511\\单型号贡献-低效-长尾\\物流发货\\2025年7月明细.xlsx'), ('2025年8月明细.xlsx', '8月明细', 'D:\\000物料报表\\202511\\单型号贡献-低效-长尾\\物流发货\\2025年8月明细.xlsx'), ('2025年9月明细.xlsx', '9月明细', 'D:\\000物料报表\\202511\\单型号贡献-低效-长尾\\物流发货\\2025年9月明细.xlsx')]

In [107]:
#如果有报错请提示报错信息
df = pd.DataFrame()
for file in excel_files:
    try:
        df_temp = pd.read_excel(file[2], sheet_name=file[1])
        df_temp['发货月份'] = file[0][:8]
        print(f'成功读取{file[0]}的{file[1]}表')
    except:
        print(f'读取{file[0]}的{file[1]}表失败')
    if '实际总数量' in df_temp.columns:
        df_temp = df_temp.rename(columns={'实际总数量':'实际出库数量'})
    df_temp = df_temp[['商品编码', '渠道', '实际出库数量','发货月份','收货仓','发货仓']]
    df = pd.concat([df, df_temp], axis=0).reset_index(drop=True)
df = df.dropna(how='all').reset_index(drop=True)  # 仅当一行所有值都是NaN时才删除
df['商品编码'] = df['商品编码'].astype(str)
df['渠道'].value_counts()

成功读取2025年10月明细.xlsx的10月明细表
成功读取2025年11月明细.xlsx的11月明细表
成功读取2025年1月明细.xlsx的1月明细表
成功读取2025年2月明细.xlsx的2月明细表
成功读取2025年3月明细.xlsx的3月明细表
成功读取2025年4月明细.xlsx的4月明细表
成功读取2025年5月明细.xlsx的5月明细表
成功读取2025年6月明细.xlsx的6月明细表
成功读取2025年7月明细.xlsx的7月明细表
成功读取2025年8月明细.xlsx的8月明细表
成功读取2025年9月明细.xlsx的9月明细表

渠道
零售        439020
工程         18943
电商          9050
电商不可售       6616
海外          1924
每誉           155
战略电商         129
新品            67
内部处理通用        15
借出渠道          14
商净             7
渠道             4
调出渠道           2
转出渠道           2
米博新零售          1
Name: count, dtype: int64

In [108]:
df['物料编码'] = df['商品编码'].astype(str)
df['渠道'] = df['渠道'].map(Channel_map).fillna('非零售工程电商')
df = df[(df['渠道']!='无') & 
        (df['物料编码'].str.len()>=10)
        ].reset_index(drop=True)
df['渠道'].value_counts()

渠道
零售       439020
工程        18943
电商        15877
海外         1924
每誉          155
商净            7
米博新零售         1
Name: count, dtype: int64

In [109]:
df0  = df[['物料编码','渠道','实际出库数量','发货月份','收货仓','发货仓']]
df0['发货月份'] = df0['发货月份'].str.replace('明','')
df0['发货月份'] = pd.to_datetime(df0['发货月份'],format=r'%Y年%m月')
df0 = df0[df0['渠道'].isin(['零售','电商','工程'])].reset_index(drop=True)
df0

C:\Users\zhangbon\AppData\Local\Temp\ipykernel_21072\417966062.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df0['发货月份'] = df0['发货月份'].str.replace('明','')
C:\Users\zhangbon\AppData\Local\Temp\ipykernel_21072\417966062.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df0['发货月份'] = pd.to_datetime(df0['发货月份'],format=r'%Y年%m月')

                 物料编码  渠道 实际出库数量       发货月份      收货仓          发货仓
0       1001001500116  零售     12 2025-10-01  浙江大区杭州库     第一工业园立体仓
1       1009000600033  零售      1 2025-10-01  浙江大区杭州库     第一工业园立体仓
2       1009000500035  零售      3 2025-10-01  浙江大区杭州库     第一工业园立体仓
3       1001001500131  零售      6 2025-10-01  浙江大区杭州库     第一工业园立体仓
4       1002003700049  零售      5 2025-10-01  浙江大区杭州库     第一工业园立体仓
...               ...  ..    ...        ...      ...          ...
473835  1124000203000  零售     -1 2025-09-01    电商丰树仓  第二工业园290立体仓
473836  1124000207630  电商      6 2025-09-01    电商丰树仓  第二工业园290立体仓
473837  1124000207630  零售     -6 2025-09-01    电商丰树仓  第二工业园290立体仓
473838  1124000207640  电商      6 2025-09-01    电商丰树仓  第二工业园290立体仓
473839  1124000207640  零售     -6 2025-09-01    电商丰树仓  第二工业园290立体仓

[473840 rows x 6 columns]

In [112]:
df0 = df0[~df0['发货仓'].isnull()].reset_index(drop=True)
df0

                 物料编码  渠道 实际出库数量       发货月份      收货仓          发货仓
0       1001001500116  零售     12 2025-10-01  浙江大区杭州库     第一工业园立体仓
1       1009000600033  零售      1 2025-10-01  浙江大区杭州库     第一工业园立体仓
2       1009000500035  零售      3 2025-10-01  浙江大区杭州库     第一工业园立体仓
3       1001001500131  零售      6 2025-10-01  浙江大区杭州库     第一工业园立体仓
4       1002003700049  零售      5 2025-10-01  浙江大区杭州库     第一工业园立体仓
...               ...  ..    ...        ...      ...          ...
472763  1124000203000  零售     -1 2025-09-01    电商丰树仓  第二工业园290立体仓
472764  1124000207630  电商      6 2025-09-01    电商丰树仓  第二工业园290立体仓
472765  1124000207630  零售     -6 2025-09-01    电商丰树仓  第二工业园290立体仓
472766  1124000207640  电商      6 2025-09-01    电商丰树仓  第二工业园290立体仓
472767  1124000207640  零售     -6 2025-09-01    电商丰树仓  第二工业园290立体仓

[472768 rows x 6 columns]

In [ ]:
# 这里是为了对BI的数据，所以包含了慈溪仓的数据
df1 = df0.groupby(['物料编码','渠道','发货月份'],as_index=False).agg(
    实际出库数量=('实际出库数量','sum'),
).sort_values('发货月份').reset_index(drop=True)
df1

                物料编码  渠道       发货月份 实际出库数量
0      1001000200087  零售 2025-01-01      1
1      1005000900003  零售 2025-01-01    254
2      1006000300019  工程 2025-01-01      1
3      1001001500130  电商 2025-01-01      1
4      1006000300057  零售 2025-01-01     83
...              ...  ..        ...    ...
12322  1001000900407  电商 2025-11-01    200
12323  1009000500020  零售 2025-11-01     37
12324  1001000900410  电商 2025-11-01      1
12325  1001000900410  零售 2025-11-01   1191
12326  1124000207780  工程 2025-11-01      7

[12327 rows x 4 columns]

In [114]:
df1.to_excel(r'C:\Users\zhangbon\Desktop\产品渠道信息-实际出库数量.xlsx',index=False)

### 产品渠道状态缺失分析

In [205]:
#将这些excel的表格数据进行上下拼接，只要字段：商品编码、商品名称、渠道、实际出库数量
folder_path = fr"D:\000物料报表\202511\单型号贡献-低效-长尾\物流发货"  # 请替换为实际的文件夹路径
excel_files = []
for root, dirs, files in os.walk(folder_path):
    for file in files:
        sheet_names = file[5:].replace(file[-5:],'')
        if (file.endswith('.xlsx') or file.endswith('.xls')) and not file.startswith('~$'):
            file_path = os.path.join(root, file)
            excel_files.append((file, sheet_names, file_path))
print(excel_files)

[('2025年10月明细.xlsx', '10月明细', 'D:\\000物料报表\\202511\\单型号贡献-低效-长尾\\物流发货\\2025年10月明细.xlsx'), ('2025年11月明细.xlsx', '11月明细', 'D:\\000物料报表\\202511\\单型号贡献-低效-长尾\\物流发货\\2025年11月明细.xlsx'), ('2025年1月明细.xlsx', '1月明细', 'D:\\000物料报表\\202511\\单型号贡献-低效-长尾\\物流发货\\2025年1月明细.xlsx'), ('2025年2月明细.xlsx', '2月明细', 'D:\\000物料报表\\202511\\单型号贡献-低效-长尾\\物流发货\\2025年2月明细.xlsx'), ('2025年3月明细.xlsx', '3月明细', 'D:\\000物料报表\\202511\\单型号贡献-低效-长尾\\物流发货\\2025年3月明细.xlsx'), ('2025年4月明细.xlsx', '4月明细', 'D:\\000物料报表\\202511\\单型号贡献-低效-长尾\\物流发货\\2025年4月明细.xlsx'), ('2025年5月明细.xlsx', '5月明细', 'D:\\000物料报表\\202511\\单型号贡献-低效-长尾\\物流发货\\2025年5月明细.xlsx'), ('2025年6月明细.xlsx', '6月明细', 'D:\\000物料报表\\202511\\单型号贡献-低效-长尾\\物流发货\\2025年6月明细.xlsx'), ('2025年7月明细.xlsx', '7月明细', 'D:\\000物料报表\\202511\\单型号贡献-低效-长尾\\物流发货\\2025年7月明细.xlsx'), ('2025年8月明细.xlsx', '8月明细', 'D:\\000物料报表\\202511\\单型号贡献-低效-长尾\\物流发货\\2025年8月明细.xlsx'), ('2025年9月明细.xlsx', '9月明细', 'D:\\000物料报表\\202511\\单型号贡献-低效-长尾\\物流发货\\2025年9月明细.xlsx')]

In [206]:
#如果有报错请提示报错信息
df = pd.DataFrame()
for file in excel_files:
    try:
        df_temp = pd.read_excel(file[2], sheet_name=file[1])
        df_temp['发货月份'] = file[0][:8]
        print(f'成功读取{file[0]}的{file[1]}表')
    except:
        print(f'读取{file[0]}的{file[1]}表失败')
    if '实际总数量' in df_temp.columns:
        df_temp = df_temp.rename(columns={'实际总数量':'实际出库数量'})
    df_temp = df_temp[['商品编码', '渠道', '实际出库数量','发货月份','收货仓','发货仓']]
    df = pd.concat([df, df_temp], axis=0).reset_index(drop=True)
df = df.dropna(how='all').reset_index(drop=True)  # 仅当一行所有值都是NaN时才删除
df['商品编码'] = df['商品编码'].astype(str)
df['渠道'].value_counts()

成功读取2025年10月明细.xlsx的10月明细表
成功读取2025年11月明细.xlsx的11月明细表
成功读取2025年1月明细.xlsx的1月明细表
成功读取2025年2月明细.xlsx的2月明细表
成功读取2025年3月明细.xlsx的3月明细表
成功读取2025年4月明细.xlsx的4月明细表
成功读取2025年5月明细.xlsx的5月明细表
成功读取2025年6月明细.xlsx的6月明细表
成功读取2025年7月明细.xlsx的7月明细表
成功读取2025年8月明细.xlsx的8月明细表
成功读取2025年9月明细.xlsx的9月明细表

渠道
零售        439020
工程         18943
电商          9050
电商不可售       6616
海外          1924
每誉           155
战略电商         129
新品            67
内部处理通用        15
借出渠道          14
商净             7
渠道             4
调出渠道           2
转出渠道           2
米博新零售          1
Name: count, dtype: int64

In [207]:
df['物料编码'] = df['商品编码'].astype(str)
df['渠道'] = df['渠道'].map(Channel_map).fillna('非零售工程电商')
df = df[(df['渠道']!='无') & 
        (df['物料编码'].str.len()>=10)
        ].reset_index(drop=True)
df['渠道'].value_counts()

渠道
零售       439020
工程        18943
电商        15877
海外         1924
每誉          155
商净            7
米博新零售         1
Name: count, dtype: int64

In [208]:
df0  = df[['物料编码','渠道','实际出库数量','发货月份','收货仓','发货仓']]
df0['发货月份'] = df0['发货月份'].str.replace('明','')
df0['发货月份'] = pd.to_datetime(df0['发货月份'],format=r'%Y年%m月')
df0 = df0[df0['渠道'].isin(['零售','电商','工程'])].reset_index(drop=True) 
df0

C:\Users\zhangbon\AppData\Local\Temp\ipykernel_21072\1087711583.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df0['发货月份'] = df0['发货月份'].str.replace('明','')
C:\Users\zhangbon\AppData\Local\Temp\ipykernel_21072\1087711583.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df0['发货月份'] = pd.to_datetime(df0['发货月份'],format=r'%Y年%m月')

                 物料编码  渠道 实际出库数量       发货月份      收货仓          发货仓
0       1001001500116  零售     12 2025-10-01  浙江大区杭州库     第一工业园立体仓
1       1009000600033  零售      1 2025-10-01  浙江大区杭州库     第一工业园立体仓
2       1009000500035  零售      3 2025-10-01  浙江大区杭州库     第一工业园立体仓
3       1001001500131  零售      6 2025-10-01  浙江大区杭州库     第一工业园立体仓
4       1002003700049  零售      5 2025-10-01  浙江大区杭州库     第一工业园立体仓
...               ...  ..    ...        ...      ...          ...
473835  1124000203000  零售     -1 2025-09-01    电商丰树仓  第二工业园290立体仓
473836  1124000207630  电商      6 2025-09-01    电商丰树仓  第二工业园290立体仓
473837  1124000207630  零售     -6 2025-09-01    电商丰树仓  第二工业园290立体仓
473838  1124000207640  电商      6 2025-09-01    电商丰树仓  第二工业园290立体仓
473839  1124000207640  零售     -6 2025-09-01    电商丰树仓  第二工业园290立体仓

[473840 rows x 6 columns]

In [209]:
# 筛选掉调拨的部分，也就是发货仓为空的数据
df0 = df0[~df0['发货仓'].isnull()].reset_index(drop=True)
df0
# 筛选掉家人购的部分，也就是收货仓是R慈溪电商仓的
df0 = df0[df0['收货仓'] != 'R慈溪电商仓'].reset_index(drop=True).reset_index(drop=True)
df0 = df0[df0['实际出库数量'] != 0].reset_index(drop=True).reset_index(drop=True)
df0

                 物料编码  渠道 实际出库数量       发货月份      收货仓          发货仓
0       1001001500116  零售     12 2025-10-01  浙江大区杭州库     第一工业园立体仓
1       1009000600033  零售      1 2025-10-01  浙江大区杭州库     第一工业园立体仓
2       1009000500035  零售      3 2025-10-01  浙江大区杭州库     第一工业园立体仓
3       1001001500131  零售      6 2025-10-01  浙江大区杭州库     第一工业园立体仓
4       1002003700049  零售      5 2025-10-01  浙江大区杭州库     第一工业园立体仓
...               ...  ..    ...        ...      ...          ...
472324  1124000203000  零售     -1 2025-09-01    电商丰树仓  第二工业园290立体仓
472325  1124000207630  电商      6 2025-09-01    电商丰树仓  第二工业园290立体仓
472326  1124000207630  零售     -6 2025-09-01    电商丰树仓  第二工业园290立体仓
472327  1124000207640  电商      6 2025-09-01    电商丰树仓  第二工业园290立体仓
472328  1124000207640  零售     -6 2025-09-01    电商丰树仓  第二工业园290立体仓

[472329 rows x 6 columns]

In [210]:
df1 = df0.groupby(['物料编码','渠道','发货月份'],as_index=False).agg(
                                                    出库数量 = ('实际出库数量',sum),
).reset_index(drop=True)
df1

C:\Users\zhangbon\AppData\Local\Temp\ipykernel_21072\244893267.py:1: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  df1 = df0.groupby(['物料编码','渠道','发货月份'],as_index=False).agg(

                物料编码  渠道       发货月份 出库数量
0      1001000200087  零售 2025-01-01    1
1      1001000200087  零售 2025-03-01    2
2      1001000200087  零售 2025-04-01    1
3      1001000200087  零售 2025-05-01    1
4      1001000200087  零售 2025-06-01    2
...              ...  ..        ...  ...
12225  1124000207770  工程 2025-11-01    8
12226  1124000207780  工程 2025-08-01    4
12227  1124000207780  工程 2025-09-01   12
12228  1124000207780  工程 2025-10-01    6
12229  1124000207780  工程 2025-11-01    7

[12230 rows x 4 columns]

In [211]:
plm = pd.read_excel(r'D:\000物料报表\202511\单型号贡献-低效-长尾\产品生命周期状态全表.xlsx') 
plm.columns
plm['物料编码'] = plm['物料号'].astype(str).str[:13]
plm['开始销售时间'] = pd.to_datetime(plm['开始销售时间'],format='mixed')
plm['渠道'] = plm['下属渠道']
plm = plm[['物料编码','渠道','对应渠道状态','开始销售时间','产品状态','产品型号']]
plm

e:\python\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

               物料编码   渠道 对应渠道状态 开始销售时间  产品状态              产品型号
0               nan   零售     未售    NaT    开发         02-CS34BW
1               nan   电商     未售    NaT    开发         02-CS34BW
2               nan   工程     未售    NaT    开发         02-CS34BW
3               nan  NaN    NaN    NaT    作废                 1
4     1004000200090  NaN    NaN    NaT  停止发货  10T-JSG15-0606FR
...             ...  ...    ...    ...   ...               ...
9306            nan  NaN    NaN    NaT    开发            苍穹V6R1
9307            nan  NaN    NaN    NaT    量产            轩辕V1R1
9308            nan  NaN    NaN    NaT    样机         轩辕V1R1C02
9309            nan  NaN    NaN    NaT    开发         轩辕V1R1C03
9310            nan  NaN    NaN    NaT    量产            长琴V1R1

[9311 rows x 6 columns]

In [212]:
df_merge = pd.merge(df1,plm,on=['物料编码','渠道'],how='left')
df_merge

,物料编码,渠道,发货月份,出库数量,对应渠道状态,开始销售时间,产品状态,产品型号
0,1001000200087,零售,2025-01-01,1,在售,2018-05-18 12:00:00,量产,CXW-258-EA06
1,1001000200087,零售,2025-03-01,2,在售,2018-05-18 12:00:00,量产,CXW-258-EA06
2,1001000200087,零售,2025-04-01,1,在售,2018-05-18 12:00:00,量产,CXW-258-EA06
3,1001000200087,零售,2025-05-01,1,在售,2018-05-18 12:00:00,量产,CXW-258-EA06
4,1001000200087,零售,2025-06-01,2,在售,2018-05-18 12:00:00,量产,CXW-258-EA06
...,...,...,...,...,...,...,...,...
12225,1124000207770,工程,2025-11-01,8,NaN,NaT,NaN,NaN
12226,1124000207780,工程,2025-08-01,4,NaN,NaT,NaN,NaN
12227,1124000207780,工程,2025-09-01,12,NaN,NaT,NaN,NaN
12228,1124000207780,工程,2025-10-01,6,NaN,NaT,NaN,NaN
12229,1124000207780,工程,2025-11-01,7,NaN,NaT,NaN,NaN

In [213]:
df_fiflte = df_merge[df_merge['对应渠道状态'].isnull()].reset_index(drop=True)
df_fiflte

               物料编码  渠道       发货月份 出库数量 对应渠道状态 开始销售时间 产品状态 产品型号
0     1001000500361  工程 2025-02-01    1    NaN    NaT  NaN  NaN
1     1001000500363  电商 2025-07-01   10    NaN    NaT  NaN  NaN
2     1001000500372  电商 2025-05-01  104    NaN    NaT  NaN  NaN
3     1001000500372  电商 2025-07-01  145    NaN    NaT  NaN  NaN
4     1001000500372  电商 2025-08-01  172    NaN    NaT  NaN  NaN
...             ...  ..        ...  ...    ...    ...  ...  ...
1523  1124000207770  工程 2025-11-01    8    NaN    NaT  NaN  NaN
1524  1124000207780  工程 2025-08-01    4    NaN    NaT  NaN  NaN
1525  1124000207780  工程 2025-09-01   12    NaN    NaT  NaN  NaN
1526  1124000207780  工程 2025-10-01    6    NaN    NaT  NaN  NaN
1527  1124000207780  工程 2025-11-01    7    NaN    NaT  NaN  NaN

[1528 rows x 8 columns]

In [214]:
df_fiflte = df_fiflte.sort_values(by=['物料编码','渠道','发货月份'],ascending=[True,True,False]).reset_index(drop=True)
df_fiflte

               物料编码  渠道       发货月份 出库数量 对应渠道状态 开始销售时间 产品状态 产品型号
0     1001000500361  工程 2025-02-01    1    NaN    NaT  NaN  NaN
1     1001000500363  电商 2025-07-01   10    NaN    NaT  NaN  NaN
2     1001000500372  电商 2025-08-01  172    NaN    NaT  NaN  NaN
3     1001000500372  电商 2025-07-01  145    NaN    NaT  NaN  NaN
4     1001000500372  电商 2025-05-01  104    NaN    NaT  NaN  NaN
...             ...  ..        ...  ...    ...    ...  ...  ...
1523  1124000207770  工程 2025-08-01    3    NaN    NaT  NaN  NaN
1524  1124000207780  工程 2025-11-01    7    NaN    NaT  NaN  NaN
1525  1124000207780  工程 2025-10-01    6    NaN    NaT  NaN  NaN
1526  1124000207780  工程 2025-09-01   12    NaN    NaT  NaN  NaN
1527  1124000207780  工程 2025-08-01    4    NaN    NaT  NaN  NaN

[1528 rows x 8 columns]

In [219]:
df_res = df_fiflte.groupby(['物料编码','渠道'],as_index=False).agg(
                                        最后一次发货时间 = ('发货月份','first'),
                                        最后一次发货数量 = ('出库数量','first'),                                     
)
df_res1 = pd.merge(df_res,plm[['物料编码','产品状态','产品型号']].drop_duplicates(),on='物料编码',how='left')
df_res1.to_excel(rf'C:\Users\zhangbon\Desktop\缺少渠道信息-剔除了家人购-25年1月-25年11月-2.xlsx',index=False)

In [203]:
df_res

              物料编码  渠道   最后一次发货时间 最后一次发货数量
0    1001000500361  工程 2025-02-01        1
1    1001000500363  电商 2025-07-01       10
2    1001000500372  电商 2025-08-01      172
3    1001000500375  电商 2025-01-01        9
4    1001000500376  电商 2025-06-01       90
..             ...  ..        ...      ...
340  1124000207660  零售 2025-11-01        5
341  1124000207690  工程 2025-11-01        7
342  1124000207710  工程 2025-11-01        8
343  1124000207770  工程 2025-11-01        8
344  1124000207780  工程 2025-11-01        7

[345 rows x 4 columns]

               物料编码  渠道       发货月份 出库数量 对应渠道状态 开始销售时间 产品状态
1506  1124000207660  工程 2025-11-01    5    NaN    NaT  NaN
1507  1124000207660  工程 2025-10-01    1    NaN    NaT  NaN
1508  1124000207660  工程 2025-09-01    3    NaN    NaT  NaN
1509  1124000207660  电商 2025-10-01    2    NaN    NaT  NaN
1510  1124000207660  零售 2025-11-01    5    NaN    NaT  NaN
1511  1124000207660  零售 2025-10-01    5    NaN    NaT  NaN